define([], function () {
  return {
    "PropertyPaneDescription": "",
    "BasicGroupName": "HTML File Configuration",
    "HtmlConfigurationNote": "Choose either an HTML file URL or pasted HTML code. Pasted code is limited to 750 KB.",
    "HtmlFileUrlLabel": "HTML File URL",
    "HtmlFileUrlDescription": "Enter the URL to your HTML file. This can be a site-relative path (e.g., /SiteAssets/mypage.html) or a full URL.",
    "HtmlFileUrlPlaceholder": "/SiteAssets/example.html",
    "HtmlCodeLabel": "HTML Code",
    "HtmlCodeDescription": "Paste your HTML code directly here to bypass file loading. If provided, this takes precedence over the File URL.",
    "HtmlCodePlaceholder": "<!DOCTYPE html><html>...</html>",
    "FullScreenLabel": "Full Screen Mode",
    "FullScreenDescription": "Maximize the web part to cover the entire page (hides SharePoint navigation).",
    "FullScreenHotkeyWarning": "Warning: Full Screen Mode hides the SharePoint edit controls. Use Ctrl+Alt+Shift+E to reopen the Edit panel and get back to this settings page.",
    "IframeHeightLabel": "Height",
    "IframeHeightDescription": "Height of the rendered content area (e.g., 600px, 100vh, auto)",
    "DataverseEnvironmentUrlLabel": "Dataverse Environment URL",
    "DataverseEnvironmentUrlDescription": "Optional. Enter the base URL for a Dataverse environment to enable window.firepit.dataverse.fetch() for hosted apps.",
    "DataverseEnvironmentUrlPlaceholder": "https://org.crm.dynamics.com",
    "SandboxModeLabel": "Security Mode",
    "SandboxStrict": "Strict (scripts only)",
    "SandboxStandard": "Standard (scripts, modals, popups)",
    "SandboxPermissive": "Permissive (includes forms & same-origin)",
    "LockDownLabel": "Lock Down Mode",
    "LockDownDescription": "Blocks connectivty between your html file and SharePoint",
    "PlaceholderTitle": "Firepit",
    "PlaceholderDescription": "Configure this web part to display an HTML file from your SharePoint site. Click 'Edit' and set the HTML File URL in the property pane.",
    "LoadingMessage": "Loading HTML content...",
    "ErrorTitle": "Failed to Load Content",
    "RetryButton": "Try Again",
    "HttpErrorPrefix": "HTTP Error",
    "UnknownError": "An unknown error occurred while loading the HTML file."
  }
});
