const advancedDebugTab = {
    _setSafeContent(el, html) {
        const parser = new DOMParser();
        const doc = parser.parseFromString(html, 'text/html');
        const frag = document.createDocumentFragment();
        Array.from(doc.body.childNodes).forEach(n => frag.appendChild(n));
        el.replaceChildren(frag);
    },

    init() {
        const pane = document.getElementById('advanced-debug');
        if (!pane) return;
        this._setSafeContent(pane, this.renderBase());
        this.bind();

        $('#advanced-debug-tab').on('shown.bs.tab', () => this.checkStatus());
        if ($('#advanced-debug').hasClass('active') || $('#advanced-debug').hasClass('show')) {
            this.checkStatus();
        }
    },

    renderBase() {
        return `
            <h3>Advanced Debug Recorder</h3>
            <p>Capture a deep, AI-friendly debugging timeline from a running offline app: user interactions, console output, errors, network calls, storage/history changes, DOM mutations, state snapshots, and instrumented callback inputs/outputs.</p>

            <div class="integration-section mb-4" id="advanced-debug-integration-panel">
                <h4>Integration</h4>
                <div id="advanced-debug-status" class="d-flex align-items-center p-3 rounded"
                    style="background-color: #343a40; border: 1px solid #495057;">
                    <span class="status-badge mr-3" id="advanced-debug-status-badge">Checking...</span>
                    <span id="advanced-debug-status-message" class="flex-grow-1">Checking if advanceddebug.js is integrated...</span>
                    <button id="advanced-debug-refresh-status-btn" class="btn btn-sm btn-outline-secondary ml-2">Refresh</button>
                </div>
                <div class="actions-section mt-3">
                    <button id="advanced-debug-copy-btn" class="btn btn-info">Copy advanceddebug.js Code</button>
                    <button id="advanced-debug-add-btn" class="btn btn-success" disabled>Add advanceddebug.js to Project</button>
                    <button id="advanced-debug-update-btn" class="btn btn-warning" style="display:none;">Update advanceddebug.js</button>
                    <div id="advanced-debug-progress" class="progress-indicator" aria-live="polite" style="display:none;">
                        <span class="spinner" aria-hidden="true"></span>
                        <span id="advanced-debug-progress-text">Preparing integration...</span>
                    </div>
                </div>
                <div class="mt-3 small" style="line-height:1.35;">
                    Add this script near the top of each page. Open your app and press <kbd>Ctrl/Cmd + Alt + D</kbd> to copy or download the captured AI context file.
                </div>
            </div>

            <hr class="my-4">

            <div class="ai-prompt-section">
                <h4>Optional App Instrumentation</h4>
                <p class="text-muted">The recorder automatically wraps event listeners and timers loaded after it. For direct business-logic functions or app state, add explicit hooks like these.</p>
                <div class="position-relative">
                    <textarea id="advanced-debug-sample" class="form-control" rows="12" readonly style="font-family: monospace; font-size: 0.85em;">
// Capture custom app state in every snapshot.
AdvancedDebug.registerStateProvider('appState', () => window.appState);

// Wrap a function to record arguments, return values, thrown errors, and promise results.
saveRecord = AdvancedDebug.trackFunction('saveRecord', saveRecord);

// Wrap all methods on a plain object.
AdvancedDebug.wrapObject(window.apiClient, 'apiClient');

// Add custom breadcrumbs anywhere.
AdvancedDebug.record('domain.step', { screen: 'checkout', id: currentId });
                    </textarea>
                    <button id="advanced-debug-copy-sample-btn" class="btn btn-sm btn-light position-absolute" style="top: 10px; right: 10px;">Copy</button>
                </div>
            </div>
        `;
    },

    bind() {
        $('#advanced-debug-refresh-status-btn').on('click', () => this.checkStatus());
        $('#advanced-debug-copy-btn').on('click', () => this.copyAdvancedDebugCode());
        $('#advanced-debug-add-btn').on('click', () => this.integrate(false));
        $('#advanced-debug-update-btn').on('click', () => this.integrate(true));
        $('#advanced-debug-copy-sample-btn').on('click', () => {
            const text = document.getElementById('advanced-debug-sample').value;
            if (!text) return;
            navigator.clipboard.writeText(text);
            const btn = $('#advanced-debug-copy-sample-btn');
            const orig = btn.text();
            btn.text('Copied');
            setTimeout(() => btn.text(orig), 1500);
        });
    },

    async checkStatus() {
        const statusBadge = $('#advanced-debug-status-badge');
        const statusMessage = $('#advanced-debug-status-message');
        const addBtn = $('#advanced-debug-add-btn');
        const updateBtn = $('#advanced-debug-update-btn');

        addBtn.prop('disabled', true).show();
        updateBtn.hide();
        statusBadge.text('Checking...').attr('class', 'status-badge checking');
        statusMessage.text('Checking if advanceddebug.js is integrated...');

        if (!loadFolder || !loadFolder.fileHandle) {
            statusBadge.text('No Project').attr('class', 'status-badge not-found');
            statusMessage.text('Load a directory first to check integration.');
            return;
        }

        const files = Array.isArray(loadFolder.fileStructure) ? loadFolder.fileStructure : [];
        const debugFile = files.find(f => f.name === 'advanceddebug.js');
        const htmlFiles = files.filter(f => f && f.kind === 'file' && /\.html?$/i.test(f.name || ''));

        if (debugFile) {
            statusBadge.text('Found').attr('class', 'status-badge found');
            addBtn.hide();
            updateBtn.show();
        } else {
            statusBadge.text('Not Found').attr('class', 'status-badge not-found');
            addBtn.prop('disabled', false).show();
            updateBtn.hide();
        }

        const tagStatus = await this._countHtmlScriptTags(htmlFiles);
        if (debugFile && tagStatus.withTag < tagStatus.total) {
            statusMessage.text('advanceddebug.js is present; ' + tagStatus.withTag + ' of ' + tagStatus.total + ' HTML files include it. Click Update to inject missing tags.');
        } else if (debugFile) {
            statusMessage.text('advanceddebug.js is present and script tags are integrated.');
        } else {
            statusMessage.text('advanceddebug.js is not yet integrated in your project.');
        }
    },

    async _countHtmlScriptTags(htmlFiles) {
        const result = { total: htmlFiles.length, withTag: 0 };
        for (const file of htmlFiles) {
            try {
                const content = await this._readFileContent(file);
                if (/advanceddebug\.js/i.test(content)) result.withTag += 1;
            } catch (err) {
                console.warn('AdvancedDebug: could not inspect HTML file', file.relativePath || file.name, err);
            }
        }
        return result;
    },
    getEmbeddedAdvancedDebugCode() {
        return decodeURIComponent(escape(atob('LyogQWR2YW5jZWQgRGVidWcgUmVjb3JkZXIgLSBnZW5lcmF0ZWQgYnkgRm9yZ2UgKi8KKGZ1bmN0aW9uICgpIHsKICBpZiAod2luZG93Ll9fYWR2YW5jZWREZWJ1Z0luc3RhbGxlZCkgcmV0dXJuOwogIHdpbmRvdy5fX2FkdmFuY2VkRGVidWdJbnN0YWxsZWQgPSB0cnVlOwoKICBjb25zdCBDT05GSUcgPSBPYmplY3QuYXNzaWduKHsKICAgIGF1dG9TdGFydDogdHJ1ZSwKICAgIG1heEV2ZW50czogMjAwMDAsCiAgICBtYXhTdHJpbmc6IDQwMDAsCiAgICBtYXhEZXB0aDogNSwKICAgIHNuYXBzaG90SW50ZXJ2YWxNczogNTAwMCwKICAgIGNhcHR1cmVEb21NdXRhdGlvbnM6IHRydWUsCiAgICBjYXB0dXJlU3RvcmFnZVZhbHVlczogdHJ1ZSwKICAgIGNhcHR1cmVHbG9iYWxTdGF0ZTogdHJ1ZSwKICAgIHN0YXRlS2V5czogW10KICB9LCB3aW5kb3cuX19BRFZBTkNFRF9ERUJVR19DT05GSUdfXyB8fCB7fSk7CgogIGNvbnN0IE5TID0gJ2Fkdi1kZWJ1Zyc7CiAgY29uc3QgVUlfQ0xBU1MgPSAnYWR2LWRlYnVnLXVpJzsKICBjb25zdCBTRU5TSVRJVkVfUkUgPSAvKHBhc3N3b3JkfHBhc3N3ZHxwd2R8c2VjcmV0fHRva2VufGFwaVstX10/a2V5fGF1dGhvcml6YXRpb258YXV0aHxiZWFyZXJ8Y29va2llfHNlc3Npb258Y3JlZGVudGlhbHxwcml2YXRlfHNzbnxjcmVkaXR8Y2FyZHxjdnYpL2k7CiAgY29uc3Qgb3JpZ2luYWwgPSB7fTsKICBjb25zdCBsaXN0ZW5lck1hcCA9IG5ldyBXZWFrTWFwKCk7CiAgY29uc3Qgc3RhdGVQcm92aWRlcnMgPSBuZXcgTWFwKCk7CgogIGNvbnN0IHN0YXRlID0gewogICAgcmVjb3JkaW5nOiAhIUNPTkZJRy5hdXRvU3RhcnQsCiAgICBzdGFydGVkQXQ6IG5ldyBEYXRlKCkudG9JU09TdHJpbmcoKSwKICAgIHNlc3Npb25JZDogJ2FkdmRiZy0nICsgRGF0ZS5ub3coKS50b1N0cmluZygzNikgKyAnLScgKyBNYXRoLnJhbmRvbSgpLnRvU3RyaW5nKDM2KS5zbGljZSgyLCA4KSwKICAgIGV2ZW50czogW10sCiAgICBzbmFwc2hvdHM6IFtdLAogICAgY291bnRlcnM6IHt9LAogICAgcGFuZWw6IG51bGwsCiAgICBzdGF0dXM6IG51bGwsCiAgICBvdXRwdXQ6IG51bGwsCiAgICBzbmFwc2hvdFRpbWVyOiBudWxsLAogICAgbXV0YXRpb25PYnNlcnZlcjogbnVsbCwKICAgIGxhc3RTY3JvbGxBdDogMCwKICAgIGxhc3RQb2ludGVyQXQ6IDAsCiAgICBsYXN0SW5wdXRCeVNlbGVjdG9yOiBuZXcgTWFwKCkKICB9OwoKICBmdW5jdGlvbiBub3dJc28oKSB7CiAgICByZXR1cm4gbmV3IERhdGUoKS50b0lTT1N0cmluZygpOwogIH0KCiAgZnVuY3Rpb24gaW5jKHR5cGUpIHsKICAgIHN0YXRlLmNvdW50ZXJzW3R5cGVdID0gKHN0YXRlLmNvdW50ZXJzW3R5cGVdIHx8IDApICsgMTsKICB9CgogIGZ1bmN0aW9uIHJlZGFjdFZhbHVlKGtleSwgdmFsdWUpIHsKICAgIGlmIChTRU5TSVRJVkVfUkUudGVzdChTdHJpbmcoa2V5IHx8ICcnKSkpIHJldHVybiAnW1JFREFDVEVEXSc7CiAgICBpZiAodHlwZW9mIHZhbHVlID09PSAnc3RyaW5nJyAmJiBTRU5TSVRJVkVfUkUudGVzdCh2YWx1ZSkgJiYgdmFsdWUubGVuZ3RoID4gMTIpIHJldHVybiAnW1JFREFDVEVEP10nOwogICAgcmV0dXJuIHZhbHVlOwogIH0KCiAgZnVuY3Rpb24gdHJ1bmNhdGVTdHJpbmcodmFsdWUsIG1heCkgewogICAgY29uc3QgcyA9IFN0cmluZyh2YWx1ZSk7CiAgICBjb25zdCBsaW1pdCA9IG1heCB8fCBDT05GSUcubWF4U3RyaW5nOwogICAgcmV0dXJuIHMubGVuZ3RoID4gbGltaXQgPyBzLnNsaWNlKDAsIGxpbWl0KSArICcuLi5bdHJ1bmNhdGVkICcgKyAocy5sZW5ndGggLSBsaW1pdCkgKyAnIGNoYXJzXScgOiBzOwogIH0KCiAgZnVuY3Rpb24gc2FmZVNlcmlhbGl6ZSh2YWx1ZSwgb3B0cykgewogICAgY29uc3Qgb3B0aW9ucyA9IE9iamVjdC5hc3NpZ24oeyBkZXB0aDogQ09ORklHLm1heERlcHRoLCBtYXhTdHJpbmc6IENPTkZJRy5tYXhTdHJpbmcgfSwgb3B0cyB8fCB7fSk7CiAgICBjb25zdCBzZWVuID0gbmV3IFdlYWtNYXAoKTsKCiAgICBmdW5jdGlvbiBpbm5lcih2LCBkZXB0aCwga2V5KSB7CiAgICAgIHRyeSB7CiAgICAgICAgdiA9IHJlZGFjdFZhbHVlKGtleSwgdik7CiAgICAgICAgaWYgKHYgPT09IG51bGwgfHwgdiA9PT0gdW5kZWZpbmVkKSByZXR1cm4gdjsKICAgICAgICBjb25zdCB0ID0gdHlwZW9mIHY7CiAgICAgICAgaWYgKHQgPT09ICdzdHJpbmcnKSByZXR1cm4gdHJ1bmNhdGVTdHJpbmcodiwgb3B0aW9ucy5tYXhTdHJpbmcpOwogICAgICAgIGlmICh0ID09PSAnbnVtYmVyJyB8fCB0ID09PSAnYm9vbGVhbicgfHwgdCA9PT0gJ2JpZ2ludCcpIHJldHVybiBTdHJpbmcodik7CiAgICAgICAgaWYgKHQgPT09ICdzeW1ib2wnKSByZXR1cm4gU3RyaW5nKHYpOwogICAgICAgIGlmICh0ID09PSAnZnVuY3Rpb24nKSByZXR1cm4gJ1tGdW5jdGlvbiAnICsgKHYubmFtZSB8fCAnYW5vbnltb3VzJykgKyAnXSc7CiAgICAgICAgaWYgKHYgaW5zdGFuY2VvZiBFcnJvcikgewogICAgICAgICAgcmV0dXJuIHsgbmFtZTogdi5uYW1lLCBtZXNzYWdlOiB2Lm1lc3NhZ2UsIHN0YWNrOiB0cnVuY2F0ZVN0cmluZyh2LnN0YWNrIHx8ICcnLCBvcHRpb25zLm1heFN0cmluZykgfTsKICAgICAgICB9CiAgICAgICAgaWYgKHR5cGVvZiBFdmVudCAhPT0gJ3VuZGVmaW5lZCcgJiYgdiBpbnN0YW5jZW9mIEV2ZW50KSByZXR1cm4gc3VtbWFyaXplRXZlbnQodik7CiAgICAgICAgaWYgKHR5cGVvZiBFbGVtZW50ICE9PSAndW5kZWZpbmVkJyAmJiB2IGluc3RhbmNlb2YgRWxlbWVudCkgcmV0dXJuIHN1bW1hcml6ZUVsZW1lbnQodik7CiAgICAgICAgaWYgKHR5cGVvZiBOb2RlICE9PSAndW5kZWZpbmVkJyAmJiB2IGluc3RhbmNlb2YgTm9kZSkgcmV0dXJuIHsgbm9kZVR5cGU6IHYubm9kZVR5cGUsIG5vZGVOYW1lOiB2Lm5vZGVOYW1lLCB0ZXh0OiB0cnVuY2F0ZVN0cmluZyh2LnRleHRDb250ZW50IHx8ICcnLCAzMDApIH07CiAgICAgICAgaWYgKHR5cGVvZiBSZXNwb25zZSAhPT0gJ3VuZGVmaW5lZCcgJiYgdiBpbnN0YW5jZW9mIFJlc3BvbnNlKSByZXR1cm4geyB0eXBlOiAnUmVzcG9uc2UnLCB1cmw6IHYudXJsLCBzdGF0dXM6IHYuc3RhdHVzLCBzdGF0dXNUZXh0OiB2LnN0YXR1c1RleHQsIG9rOiB2Lm9rLCByZWRpcmVjdGVkOiB2LnJlZGlyZWN0ZWQgfTsKICAgICAgICBpZiAodHlwZW9mIFJlcXVlc3QgIT09ICd1bmRlZmluZWQnICYmIHYgaW5zdGFuY2VvZiBSZXF1ZXN0KSByZXR1cm4geyB0eXBlOiAnUmVxdWVzdCcsIHVybDogdi51cmwsIG1ldGhvZDogdi5tZXRob2QsIG1vZGU6IHYubW9kZSwgY3JlZGVudGlhbHM6IHYuY3JlZGVudGlhbHMgfTsKICAgICAgICBpZiAodHlwZW9mIEhlYWRlcnMgIT09ICd1bmRlZmluZWQnICYmIHYgaW5zdGFuY2VvZiBIZWFkZXJzKSB7CiAgICAgICAgICBjb25zdCBvdXQgPSB7fTsKICAgICAgICAgIHYuZm9yRWFjaCgodmFsLCBoZWFkZXIpID0+IHsgb3V0W2hlYWRlcl0gPSByZWRhY3RWYWx1ZShoZWFkZXIsIHZhbCk7IH0pOwogICAgICAgICAgcmV0dXJuIG91dDsKICAgICAgICB9CiAgICAgICAgaWYgKGRlcHRoID49IG9wdGlvbnMuZGVwdGgpIHJldHVybiBBcnJheS5pc0FycmF5KHYpID8gJ1tBcnJheSgnICsgdi5sZW5ndGggKyAnKV0nIDogJ1tPYmplY3RdJzsKICAgICAgICBpZiAoc2Vlbi5oYXModikpIHJldHVybiAnW0NpcmN1bGFyICcgKyBzZWVuLmdldCh2KSArICddJzsKICAgICAgICBzZWVuLnNldCh2LCBrZXkgfHwgJ3Jvb3QnKTsKICAgICAgICBpZiAoQXJyYXkuaXNBcnJheSh2KSkgcmV0dXJuIHYuc2xpY2UoMCwgMTAwKS5tYXAoKGl0ZW0sIGlkeCkgPT4gaW5uZXIoaXRlbSwgZGVwdGggKyAxLCBpZHgpKTsKICAgICAgICBjb25zdCBvdXQgPSB7fTsKICAgICAgICBPYmplY3Qua2V5cyh2KS5zbGljZSgwLCAxMDApLmZvckVhY2goKGspID0+IHsKICAgICAgICAgIHRyeSB7IG91dFtrXSA9IGlubmVyKHZba10sIGRlcHRoICsgMSwgayk7IH0gY2F0Y2ggKGVycikgeyBvdXRba10gPSAnW1VuaW5zcGVjdGFibGU6ICcgKyAoZXJyLm1lc3NhZ2UgfHwgZXJyKSArICddJzsgfQogICAgICAgIH0pOwogICAgICAgIGNvbnN0IGtleXMgPSBPYmplY3Qua2V5cyh2KTsKICAgICAgICBpZiAoa2V5cy5sZW5ndGggPiAxMDApIG91dC5fX3RydW5jYXRlZEtleXMgPSBrZXlzLmxlbmd0aCAtIDEwMDsKICAgICAgICByZXR1cm4gb3V0OwogICAgICB9IGNhdGNoIChlcnIpIHsKICAgICAgICByZXR1cm4gJ1tVbnNlcmlhbGl6YWJsZTogJyArIChlcnIgJiYgZXJyLm1lc3NhZ2UgPyBlcnIubWVzc2FnZSA6IFN0cmluZyhlcnIpKSArICddJzsKICAgICAgfQogICAgfQoKICAgIHJldHVybiBpbm5lcih2YWx1ZSwgMCwgJ3Jvb3QnKTsKICB9CgogIGZ1bmN0aW9uIHNhZmVDc3ModmFsdWUpIHsKICAgIGlmICh3aW5kb3cuQ1NTICYmIENTUy5lc2NhcGUpIHJldHVybiBDU1MuZXNjYXBlKFN0cmluZyh2YWx1ZSkpOwogICAgcmV0dXJuIFN0cmluZyh2YWx1ZSkucmVwbGFjZSgvW15hLXpBLVowLTlfLV0vZywgJ1xcJCYnKTsKICB9CgogIGZ1bmN0aW9uIGdldFNlbGVjdG9yKGVsKSB7CiAgICBpZiAoIWVsIHx8ICFlbC50YWdOYW1lKSByZXR1cm4gbnVsbDsKICAgIGlmIChlbC5pZCkgcmV0dXJuICcjJyArIHNhZmVDc3MoZWwuaWQpOwogICAgY29uc3QgYXR0cnMgPSBbJ2RhdGEtdGVzdGlkJywgJ2RhdGEtdGVzdCcsICdkYXRhLXFhJywgJ2RhdGEtcm9sZScsICduYW1lJywgJ2FyaWEtbGFiZWwnLCAndGl0bGUnXTsKICAgIGZvciAoY29uc3QgYXR0ciBvZiBhdHRycykgewogICAgICBjb25zdCB2YWwgPSBlbC5nZXRBdHRyaWJ1dGUoYXR0cik7CiAgICAgIGlmICh2YWwpIHJldHVybiBlbC50YWdOYW1lLnRvTG93ZXJDYXNlKCkgKyAnWycgKyBhdHRyICsgJz0iJyArIHNhZmVDc3ModmFsKSArICciXSc7CiAgICB9CiAgICBjb25zdCBwYXRoID0gW107CiAgICBsZXQgbm9kZSA9IGVsOwogICAgd2hpbGUgKG5vZGUgJiYgbm9kZS5ub2RlVHlwZSA9PT0gMSAmJiBub2RlICE9PSBkb2N1bWVudC5ib2R5ICYmIHBhdGgubGVuZ3RoIDwgNikgewogICAgICBjb25zdCB0YWcgPSBub2RlLnRhZ05hbWUudG9Mb3dlckNhc2UoKTsKICAgICAgbGV0IGluZGV4ID0gMTsKICAgICAgbGV0IHNpYiA9IG5vZGUucHJldmlvdXNFbGVtZW50U2libGluZzsKICAgICAgd2hpbGUgKHNpYikgewogICAgICAgIGlmIChzaWIudGFnTmFtZSAmJiBzaWIudGFnTmFtZS50b0xvd2VyQ2FzZSgpID09PSB0YWcpIGluZGV4Kys7CiAgICAgICAgc2liID0gc2liLnByZXZpb3VzRWxlbWVudFNpYmxpbmc7CiAgICAgIH0KICAgICAgcGF0aC51bnNoaWZ0KHRhZyArICc6bnRoLW9mLXR5cGUoJyArIGluZGV4ICsgJyknKTsKICAgICAgaWYgKG5vZGUucGFyZW50RWxlbWVudCAmJiBub2RlLnBhcmVudEVsZW1lbnQuaWQpIHsKICAgICAgICBwYXRoLnVuc2hpZnQoJyMnICsgc2FmZUNzcyhub2RlLnBhcmVudEVsZW1lbnQuaWQpKTsKICAgICAgICBicmVhazsKICAgICAgfQogICAgICBub2RlID0gbm9kZS5wYXJlbnRFbGVtZW50OwogICAgfQogICAgcmV0dXJuIHBhdGguam9pbignID4gJyk7CiAgfQoKICBmdW5jdGlvbiBpc1VpKGVsKSB7CiAgICByZXR1cm4gISEoZWwgJiYgZWwuY2xvc2VzdCAmJiBlbC5jbG9zZXN0KCcuJyArIFVJX0NMQVNTKSk7CiAgfQoKICBmdW5jdGlvbiBzdW1tYXJpemVFbGVtZW50KGVsKSB7CiAgICBpZiAoIWVsIHx8ICFlbC50YWdOYW1lKSByZXR1cm4gbnVsbDsKICAgIGNvbnN0IHJlY3QgPSB0eXBlb2YgZWwuZ2V0Qm91bmRpbmdDbGllbnRSZWN0ID09PSAnZnVuY3Rpb24nID8gZWwuZ2V0Qm91bmRpbmdDbGllbnRSZWN0KCkgOiBudWxsOwogICAgY29uc3Qgb3V0ID0gewogICAgICB0YWc6IGVsLnRhZ05hbWUudG9Mb3dlckNhc2UoKSwKICAgICAgc2VsZWN0b3I6IGdldFNlbGVjdG9yKGVsKSwKICAgICAgaWQ6IGVsLmlkIHx8ICcnLAogICAgICBjbGFzc2VzOiBTdHJpbmcoZWwuY2xhc3NOYW1lIHx8ICcnKS50cmltKCkuc3BsaXQoL1xzKy8pLmZpbHRlcihCb29sZWFuKS5zbGljZSgwLCAxMiksCiAgICAgIHRleHQ6IHRydW5jYXRlU3RyaW5nKChlbC5pbm5lclRleHQgfHwgZWwudGV4dENvbnRlbnQgfHwgJycpLnJlcGxhY2UoL1xzKy9nLCAnICcpLnRyaW0oKSwgNTAwKSwKICAgICAgcm9sZTogZWwuZ2V0QXR0cmlidXRlKCdyb2xlJykgfHwgJycsCiAgICAgIGFyaWFMYWJlbDogZWwuZ2V0QXR0cmlidXRlKCdhcmlhLWxhYmVsJykgfHwgJycsCiAgICAgIG5hbWU6IGVsLmdldEF0dHJpYnV0ZSgnbmFtZScpIHx8ICcnLAogICAgICB0eXBlOiBlbC5nZXRBdHRyaWJ1dGUoJ3R5cGUnKSB8fCAnJywKICAgICAgZGlzYWJsZWQ6ICEhZWwuZGlzYWJsZWQsCiAgICAgIGhpZGRlbjogISFlbC5oaWRkZW4KICAgIH07CiAgICBpZiAocmVjdCkgewogICAgICBvdXQucmVjdCA9IHsKICAgICAgICB4OiBNYXRoLnJvdW5kKHJlY3QueCksCiAgICAgICAgeTogTWF0aC5yb3VuZChyZWN0LnkpLAogICAgICAgIHdpZHRoOiBNYXRoLnJvdW5kKHJlY3Qud2lkdGgpLAogICAgICAgIGhlaWdodDogTWF0aC5yb3VuZChyZWN0LmhlaWdodCkKICAgICAgfTsKICAgIH0KICAgIGlmICgndmFsdWUnIGluIGVsICYmICFTRU5TSVRJVkVfUkUudGVzdCgoZWwubmFtZSB8fCAnJykgKyAnICcgKyAoZWwuaWQgfHwgJycpICsgJyAnICsgKGVsLnR5cGUgfHwgJycpKSkgewogICAgICBvdXQudmFsdWUgPSB0cnVuY2F0ZVN0cmluZyhlbC52YWx1ZSwgMTAwMCk7CiAgICB9IGVsc2UgaWYgKCd2YWx1ZScgaW4gZWwpIHsKICAgICAgb3V0LnZhbHVlID0gJ1tSRURBQ1RFRF0nOwogICAgfQogICAgaWYgKCdjaGVja2VkJyBpbiBlbCkgb3V0LmNoZWNrZWQgPSAhIWVsLmNoZWNrZWQ7CiAgICByZXR1cm4gb3V0OwogIH0KCiAgZnVuY3Rpb24gc3VtbWFyaXplRXZlbnQoZSkgewogICAgY29uc3QgdGFyZ2V0ID0gZSAmJiBlLnRhcmdldCA/IHN1bW1hcml6ZUVsZW1lbnQoZS50YXJnZXQpIDogbnVsbDsKICAgIGNvbnN0IGJhc2UgPSB7CiAgICAgIHR5cGU6IGUudHlwZSwKICAgICAgdGFyZ2V0LAogICAgICB0aW1lU3RhbXA6IE1hdGgucm91bmQoZS50aW1lU3RhbXAgfHwgMCksCiAgICAgIGRlZmF1bHRQcmV2ZW50ZWQ6ICEhZS5kZWZhdWx0UHJldmVudGVkLAogICAgICBidWJibGVzOiAhIWUuYnViYmxlcywKICAgICAgY2FuY2VsYWJsZTogISFlLmNhbmNlbGFibGUKICAgIH07CiAgICBpZiAoJ2tleScgaW4gZSkgewogICAgICBiYXNlLmtleSA9IGUua2V5OwogICAgICBiYXNlLmNvZGUgPSBlLmNvZGU7CiAgICAgIGJhc2UuY3RybEtleSA9ICEhZS5jdHJsS2V5OwogICAgICBiYXNlLmFsdEtleSA9ICEhZS5hbHRLZXk7CiAgICAgIGJhc2Uuc2hpZnRLZXkgPSAhIWUuc2hpZnRLZXk7CiAgICAgIGJhc2UubWV0YUtleSA9ICEhZS5tZXRhS2V5OwogICAgICBiYXNlLnJlcGVhdCA9ICEhZS5yZXBlYXQ7CiAgICB9CiAgICBpZiAoJ2NsaWVudFgnIGluIGUpIHsKICAgICAgYmFzZS5jbGllbnRYID0gTWF0aC5yb3VuZChlLmNsaWVudFgpOwogICAgICBiYXNlLmNsaWVudFkgPSBNYXRoLnJvdW5kKGUuY2xpZW50WSk7CiAgICAgIGJhc2UuYnV0dG9uID0gZS5idXR0b247CiAgICAgIGJhc2UuYnV0dG9ucyA9IGUuYnV0dG9uczsKICAgIH0KICAgIHJldHVybiBiYXNlOwogIH0KCiAgZnVuY3Rpb24gZ2V0RW52aXJvbm1lbnQoKSB7CiAgICByZXR1cm4gewogICAgICBocmVmOiBsb2NhdGlvbi5ocmVmLAogICAgICBvcmlnaW46IGxvY2F0aW9uLm9yaWdpbiwKICAgICAgcGF0aG5hbWU6IGxvY2F0aW9uLnBhdGhuYW1lLAogICAgICBoYXNoOiBsb2NhdGlvbi5oYXNoLAogICAgICB0aXRsZTogZG9jdW1lbnQudGl0bGUsCiAgICAgIHJlZmVycmVyOiBkb2N1bWVudC5yZWZlcnJlciwKICAgICAgdXNlckFnZW50OiBuYXZpZ2F0b3IudXNlckFnZW50LAogICAgICBsYW5ndWFnZTogbmF2aWdhdG9yLmxhbmd1YWdlLAogICAgICBwbGF0Zm9ybTogbmF2aWdhdG9yLnBsYXRmb3JtLAogICAgICBvbmxpbmU6IG5hdmlnYXRvci5vbkxpbmUsCiAgICAgIHZpc2liaWxpdHlTdGF0ZTogZG9jdW1lbnQudmlzaWJpbGl0eVN0YXRlLAogICAgICByZWFkeVN0YXRlOiBkb2N1bWVudC5yZWFkeVN0YXRlLAogICAgICB2aWV3cG9ydDogeyB3aWR0aDogd2luZG93LmlubmVyV2lkdGgsIGhlaWdodDogd2luZG93LmlubmVySGVpZ2h0LCBkZXZpY2VQaXhlbFJhdGlvOiB3aW5kb3cuZGV2aWNlUGl4ZWxSYXRpbyB8fCAxIH0sCiAgICAgIHNjcm9sbDogeyB4OiBNYXRoLnJvdW5kKHdpbmRvdy5zY3JvbGxYIHx8IDApLCB5OiBNYXRoLnJvdW5kKHdpbmRvdy5zY3JvbGxZIHx8IDApIH0sCiAgICAgIHRpbWVab25lOiBJbnRsLkRhdGVUaW1lRm9ybWF0KCkucmVzb2x2ZWRPcHRpb25zKCkudGltZVpvbmUKICAgIH07CiAgfQoKICBmdW5jdGlvbiBzYW1wbGVTdG9yYWdlKHN0b3JhZ2UsIG5hbWUpIHsKICAgIGNvbnN0IG91dCA9IHt9OwogICAgaWYgKCFzdG9yYWdlKSByZXR1cm4gb3V0OwogICAgdHJ5IHsKICAgICAgY29uc3QgbGVuID0gTWF0aC5taW4oc3RvcmFnZS5sZW5ndGggfHwgMCwgODApOwogICAgICBmb3IgKGxldCBpID0gMDsgaSA8IGxlbjsgaSsrKSB7CiAgICAgICAgY29uc3Qga2V5ID0gc3RvcmFnZS5rZXkoaSk7CiAgICAgICAgaWYgKCFrZXkpIGNvbnRpbnVlOwogICAgICAgIG91dFtrZXldID0gQ09ORklHLmNhcHR1cmVTdG9yYWdlVmFsdWVzID8gcmVkYWN0VmFsdWUoa2V5LCB0cnVuY2F0ZVN0cmluZyhzdG9yYWdlLmdldEl0ZW0oa2V5KSwgMTUwMCkpIDogJ1twcmVzZW50XSc7CiAgICAgIH0KICAgICAgaWYgKChzdG9yYWdlLmxlbmd0aCB8fCAwKSA+IGxlbikgb3V0Ll9fdHJ1bmNhdGVkS2V5cyA9IChzdG9yYWdlLmxlbmd0aCB8fCAwKSAtIGxlbjsKICAgIH0gY2F0Y2ggKGVycikgewogICAgICBvdXQuX19lcnJvciA9IG5hbWUgKyAnOiAnICsgKGVyci5tZXNzYWdlIHx8IFN0cmluZyhlcnIpKTsKICAgIH0KICAgIHJldHVybiBvdXQ7CiAgfQoKICBmdW5jdGlvbiBzYW1wbGVGb3JtcygpIHsKICAgIHJldHVybiBBcnJheS5mcm9tKGRvY3VtZW50LnF1ZXJ5U2VsZWN0b3JBbGwoJ2lucHV0LCB0ZXh0YXJlYSwgc2VsZWN0JykpLnNsaWNlKDAsIDIwMCkubWFwKChlbCkgPT4gc3VtbWFyaXplRWxlbWVudChlbCkpOwogIH0KCiAgZnVuY3Rpb24gc2FtcGxlR2xvYmFsU3RhdGUoKSB7CiAgICBjb25zdCBvdXQgPSB7fTsKICAgIGNvbnN0IGV4cGxpY2l0S2V5cyA9IEFycmF5LmlzQXJyYXkoQ09ORklHLnN0YXRlS2V5cykgPyBDT05GSUcuc3RhdGVLZXlzIDogW107CiAgICBleHBsaWNpdEtleXMuZm9yRWFjaCgoa2V5KSA9PiB7CiAgICAgIHRyeSB7IG91dFtrZXldID0gc2FmZVNlcmlhbGl6ZSh3aW5kb3dba2V5XSwgeyBkZXB0aDogNiwgbWF4U3RyaW5nOiAzMDAwIH0pOyB9IGNhdGNoIChlcnIpIHsgb3V0W2tleV0gPSAnW0Vycm9yOiAnICsgZXJyLm1lc3NhZ2UgKyAnXSc7IH0KICAgIH0pOwogICAgc3RhdGVQcm92aWRlcnMuZm9yRWFjaCgoZm4sIG5hbWUpID0+IHsKICAgICAgdHJ5IHsgb3V0W25hbWVdID0gc2FmZVNlcmlhbGl6ZShmbigpLCB7IGRlcHRoOiA2LCBtYXhTdHJpbmc6IDMwMDAgfSk7IH0gY2F0Y2ggKGVycikgeyBvdXRbbmFtZV0gPSAnW1Byb3ZpZGVyIGVycm9yOiAnICsgZXJyLm1lc3NhZ2UgKyAnXSc7IH0KICAgIH0pOwogICAgaWYgKCFDT05GSUcuY2FwdHVyZUdsb2JhbFN0YXRlKSByZXR1cm4gb3V0OwogICAgY29uc3QgY2FuZGlkYXRlcyA9IFtdOwogICAgdHJ5IHsKICAgICAgT2JqZWN0LmtleXMod2luZG93KS5mb3JFYWNoKChrZXkpID0+IHsKICAgICAgICBpZiAoZXhwbGljaXRLZXlzLmluY2x1ZGVzKGtleSkpIHJldHVybjsKICAgICAgICBpZiAoIS8oXmFwcCR8c3RhdGV8c3RvcmV8bW9kZWx8ZGF0YXxjb25maWd8Y2FjaGV8c2Vzc2lvbnxjdXJyZW50fHNlbGVjdGVkKS9pLnRlc3Qoa2V5KSkgcmV0dXJuOwogICAgICAgIGlmICgvYWR2YW5jZWRkZWJ1Z3x3ZWJwYWNrfGpxdWVyeXxib290c3RyYXB8Y29kZW1pcnJvci9pLnRlc3Qoa2V5KSkgcmV0dXJuOwogICAgICAgIGNvbnN0IHZhbHVlID0gd2luZG93W2tleV07CiAgICAgICAgaWYgKCF2YWx1ZSB8fCB0eXBlb2YgdmFsdWUgIT09ICdvYmplY3QnKSByZXR1cm47CiAgICAgICAgY2FuZGlkYXRlcy5wdXNoKGtleSk7CiAgICAgIH0pOwogICAgfSBjYXRjaCB7fQogICAgY2FuZGlkYXRlcy5zbGljZSgwLCAyNSkuZm9yRWFjaCgoa2V5KSA9PiB7CiAgICAgIHRyeSB7IG91dFtrZXldID0gc2FmZVNlcmlhbGl6ZSh3aW5kb3dba2V5XSwgeyBkZXB0aDogNCwgbWF4U3RyaW5nOiAyMDAwIH0pOyB9IGNhdGNoIChlcnIpIHsgb3V0W2tleV0gPSAnW0Vycm9yOiAnICsgZXJyLm1lc3NhZ2UgKyAnXSc7IH0KICAgIH0pOwogICAgaWYgKGNhbmRpZGF0ZXMubGVuZ3RoID4gMjUpIG91dC5fX3RydW5jYXRlZEdsb2JhbFN0YXRlS2V5cyA9IGNhbmRpZGF0ZXMubGVuZ3RoIC0gMjU7CiAgICByZXR1cm4gb3V0OwogIH0KCiAgZnVuY3Rpb24gY2FwdHVyZVNuYXBzaG90KHJlYXNvbikgewogICAgY29uc3Qgc25hcHNob3QgPSB7CiAgICAgIGlkOiBzdGF0ZS5zbmFwc2hvdHMubGVuZ3RoICsgMSwKICAgICAgdHM6IG5vd0lzbygpLAogICAgICByZWFzb246IHJlYXNvbiB8fCAnbWFudWFsJywKICAgICAgZW52OiBnZXRFbnZpcm9ubWVudCgpLAogICAgICBhY3RpdmVFbGVtZW50OiBzdW1tYXJpemVFbGVtZW50KGRvY3VtZW50LmFjdGl2ZUVsZW1lbnQpLAogICAgICBib2R5OiBkb2N1bWVudC5ib2R5ID8gewogICAgICAgIGNsYXNzZXM6IFN0cmluZyhkb2N1bWVudC5ib2R5LmNsYXNzTmFtZSB8fCAnJykudHJpbSgpLAogICAgICAgIGNoaWxkQ291bnQ6IGRvY3VtZW50LmJvZHkuY2hpbGRyZW4ubGVuZ3RoLAogICAgICAgIHRleHRMZW5ndGg6IChkb2N1bWVudC5ib2R5LmlubmVyVGV4dCB8fCBkb2N1bWVudC5ib2R5LnRleHRDb250ZW50IHx8ICcnKS5sZW5ndGgKICAgICAgfSA6IG51bGwsCiAgICAgIGZvcm1zOiBzYW1wbGVGb3JtcygpLAogICAgICBzdG9yYWdlOiBnZXRTdG9yYWdlU25hcHNob3QoKSwKICAgICAgZ2xvYmFsU3RhdGU6IHNhbXBsZUdsb2JhbFN0YXRlKCkKICAgIH07CiAgICBzdGF0ZS5zbmFwc2hvdHMucHVzaChzbmFwc2hvdCk7CiAgICBpZiAoc3RhdGUuc25hcHNob3RzLmxlbmd0aCA+IDIwMCkgc3RhdGUuc25hcHNob3RzLnNwbGljZSgwLCBzdGF0ZS5zbmFwc2hvdHMubGVuZ3RoIC0gMjAwKTsKICAgIHJlY29yZCgnc25hcHNob3QnLCB7IHJlYXNvbiwgc25hcHNob3RJZDogc25hcHNob3QuaWQgfSwgeyBmb3JjZTogdHJ1ZSwgbm9TbmFwc2hvdDogdHJ1ZSB9KTsKICAgIHJldHVybiBzbmFwc2hvdDsKICB9CgogIGZ1bmN0aW9uIGdldFN0b3JhZ2VTbmFwc2hvdCgpIHsKICAgIGNvbnN0IG91dCA9IHt9OwogICAgdHJ5IHsgb3V0LmxvY2FsU3RvcmFnZSA9IHNhbXBsZVN0b3JhZ2Uod2luZG93LmxvY2FsU3RvcmFnZSwgJ2xvY2FsU3RvcmFnZScpOyB9IGNhdGNoIChlcnIpIHsgb3V0LmxvY2FsU3RvcmFnZSA9IHsgX19lcnJvcjogZXJyLm1lc3NhZ2UgfHwgU3RyaW5nKGVycikgfTsgfQogICAgdHJ5IHsgb3V0LnNlc3Npb25TdG9yYWdlID0gc2FtcGxlU3RvcmFnZSh3aW5kb3cuc2Vzc2lvblN0b3JhZ2UsICdzZXNzaW9uU3RvcmFnZScpOyB9IGNhdGNoIChlcnIpIHsgb3V0LnNlc3Npb25TdG9yYWdlID0geyBfX2Vycm9yOiBlcnIubWVzc2FnZSB8fCBTdHJpbmcoZXJyKSB9OyB9CiAgICByZXR1cm4gb3V0OwogIH0KCiAgZnVuY3Rpb24gcmVjb3JkKHR5cGUsIGRldGFpbCwgb3B0cykgewogICAgY29uc3Qgb3B0aW9ucyA9IG9wdHMgfHwge307CiAgICBpZiAoIXN0YXRlLnJlY29yZGluZyAmJiAhb3B0aW9ucy5mb3JjZSkgcmV0dXJuOwogICAgY29uc3QgZW50cnkgPSB7CiAgICAgIGlkOiBzdGF0ZS5ldmVudHMubGVuZ3RoICsgMSwKICAgICAgdHM6IG5vd0lzbygpLAogICAgICB0eXBlLAogICAgICBzaW5jZVN0YXJ0TXM6IE1hdGgucm91bmQocGVyZm9ybWFuY2Uubm93KCkpLAogICAgICBsb2NhdGlvbjogbG9jYXRpb24uaHJlZiwKICAgICAgZGV0YWlsOiBzYWZlU2VyaWFsaXplKGRldGFpbCwgeyBkZXB0aDogb3B0aW9ucy5kZXB0aCB8fCBDT05GSUcubWF4RGVwdGgsIG1heFN0cmluZzogb3B0aW9ucy5tYXhTdHJpbmcgfHwgQ09ORklHLm1heFN0cmluZyB9KQogICAgfTsKICAgIHN0YXRlLmV2ZW50cy5wdXNoKGVudHJ5KTsKICAgIGluYyh0eXBlKTsKICAgIGlmIChzdGF0ZS5ldmVudHMubGVuZ3RoID4gQ09ORklHLm1heEV2ZW50cykgc3RhdGUuZXZlbnRzLnNwbGljZSgwLCBzdGF0ZS5ldmVudHMubGVuZ3RoIC0gQ09ORklHLm1heEV2ZW50cyk7CiAgICBpZiAoc3RhdGUuc3RhdHVzKSB1cGRhdGVTdGF0dXMoKTsKICB9CgogIGZ1bmN0aW9uIHJlY29yZEVycm9yKHR5cGUsIGVyciwgZXh0cmEpIHsKICAgIHJlY29yZCh0eXBlLCBPYmplY3QuYXNzaWduKHt9LCBleHRyYSB8fCB7fSwgeyBlcnJvcjogc2FmZVNlcmlhbGl6ZShlcnIsIHsgZGVwdGg6IDUsIG1heFN0cmluZzogODAwMCB9KSB9KSwgeyBmb3JjZTogdHJ1ZSB9KTsKICB9CgogIGZ1bmN0aW9uIGV4cG9ydFBheWxvYWQoKSB7CiAgICByZXR1cm4gewogICAgICBzY2hlbWE6ICdmb3JnZS1hZHZhbmNlZC1kZWJ1Zy1zZXNzaW9uLXYxJywKICAgICAgc3VtbWFyeTogewogICAgICAgIHNlc3Npb25JZDogc3RhdGUuc2Vzc2lvbklkLAogICAgICAgIHN0YXJ0ZWRBdDogc3RhdGUuc3RhcnRlZEF0LAogICAgICAgIGV4cG9ydGVkQXQ6IG5vd0lzbygpLAogICAgICAgIHJlY29yZGluZzogc3RhdGUucmVjb3JkaW5nLAogICAgICAgIGV2ZW50Q291bnQ6IHN0YXRlLmV2ZW50cy5sZW5ndGgsCiAgICAgICAgc25hcHNob3RDb3VudDogc3RhdGUuc25hcHNob3RzLmxlbmd0aCwKICAgICAgICBjb3VudGVyczogc3RhdGUuY291bnRlcnMKICAgICAgfSwKICAgICAgZW52aXJvbm1lbnQ6IGdldEVudmlyb25tZW50KCksCiAgICAgIG5vdGVzRm9yQWk6IFsKICAgICAgICAnVGhpcyBmaWxlIHdhcyBjYXB0dXJlZCBieSBhZHZhbmNlZGRlYnVnLmpzLicsCiAgICAgICAgJ1VzZSB0aGUgZXZlbnQgdGltZWxpbmUsIHNuYXBzaG90cywgY29uc29sZS9lcnJvci9uZXR3b3JrIHJlY29yZHMsIGFuZCBpbnN0cnVtZW50ZWQgY2FsbGJhY2svZnVuY3Rpb24gcmVjb3JkcyB0byByZWNvbnN0cnVjdCB0aGUgaXNzdWUuJywKICAgICAgICAnU2Vuc2l0aXZlLWxvb2tpbmcgdmFsdWVzIGFyZSByZWRhY3RlZCBiZXN0LWVmZm9ydC4gUGFzc3dvcmQgZmllbGRzIGFyZSBub3QgY2FwdHVyZWQuJwogICAgICBdLAogICAgICBldmVudHM6IHN0YXRlLmV2ZW50cywKICAgICAgc25hcHNob3RzOiBzdGF0ZS5zbmFwc2hvdHMKICAgIH07CiAgfQoKICBmdW5jdGlvbiBleHBvcnRUZXh0KCkgewogICAgY2FwdHVyZVNuYXBzaG90KCdleHBvcnQnKTsKICAgIHJldHVybiBKU09OLnN0cmluZ2lmeShleHBvcnRQYXlsb2FkKCksIG51bGwsIDIpOwogIH0KCiAgYXN5bmMgZnVuY3Rpb24gY29weVRleHQodGV4dCkgewogICAgdHJ5IHsKICAgICAgaWYgKG5hdmlnYXRvci5jbGlwYm9hcmQgJiYgbmF2aWdhdG9yLmNsaXBib2FyZC53cml0ZVRleHQpIHsKICAgICAgICBhd2FpdCBuYXZpZ2F0b3IuY2xpcGJvYXJkLndyaXRlVGV4dCh0ZXh0KTsKICAgICAgICByZXR1cm4gdHJ1ZTsKICAgICAgfQogICAgfSBjYXRjaCB7fQogICAgdHJ5IHsKICAgICAgY29uc3QgdGEgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCd0ZXh0YXJlYScpOwogICAgICB0YS52YWx1ZSA9IHRleHQ7CiAgICAgIHRhLnN0eWxlLnBvc2l0aW9uID0gJ2ZpeGVkJzsKICAgICAgdGEuc3R5bGUubGVmdCA9ICctOTk5OXB4JzsKICAgICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZCh0YSk7CiAgICAgIHRhLnNlbGVjdCgpOwogICAgICBjb25zdCBvayA9IGRvY3VtZW50LmV4ZWNDb21tYW5kKCdjb3B5Jyk7CiAgICAgIHRhLnJlbW92ZSgpOwogICAgICByZXR1cm4gISFvazsKICAgIH0gY2F0Y2ggewogICAgICByZXR1cm4gZmFsc2U7CiAgICB9CiAgfQoKICBmdW5jdGlvbiBkb3dubG9hZFRleHQodGV4dCkgewogICAgY29uc3QgYmxvYiA9IG5ldyBCbG9iKFt0ZXh0XSwgeyB0eXBlOiAnYXBwbGljYXRpb24vanNvbicgfSk7CiAgICBjb25zdCB1cmwgPSBVUkwuY3JlYXRlT2JqZWN0VVJMKGJsb2IpOwogICAgY29uc3QgYSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2EnKTsKICAgIGEuaHJlZiA9IHVybDsKICAgIGEuZG93bmxvYWQgPSAnYWR2YW5jZWQtZGVidWctJyArIHN0YXRlLnNlc3Npb25JZCArICcuanNvbic7CiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKGEpOwogICAgYS5jbGljaygpOwogICAgYS5yZW1vdmUoKTsKICAgIHNldFRpbWVvdXQoKCkgPT4gVVJMLnJldm9rZU9iamVjdFVSTCh1cmwpLCAxMDAwKTsKICB9CgogIGZ1bmN0aW9uIHVwZGF0ZVN0YXR1cygpIHsKICAgIGlmIChzdGF0ZS5zdGF0dXMpIHsKICAgICAgc3RhdGUuc3RhdHVzLnRleHRDb250ZW50ID0gKHN0YXRlLnJlY29yZGluZyA/ICdSZWNvcmRpbmcnIDogJ1BhdXNlZCcpICsgJyB8IEV2ZW50czogJyArIHN0YXRlLmV2ZW50cy5sZW5ndGggKyAnIHwgU25hcHNob3RzOiAnICsgc3RhdGUuc25hcHNob3RzLmxlbmd0aDsKICAgIH0KICAgIGlmIChzdGF0ZS5vdXRwdXQpIHsKICAgICAgY29uc3QgdGFpbCA9IHN0YXRlLmV2ZW50cy5zbGljZSgtMTIpLm1hcCgoZSkgPT4gJ1snICsgZS50cy5zcGxpdCgnVCcpWzFdLnJlcGxhY2UoJ1onLCAnJykgKyAnXSAnICsgZS50eXBlICsgJyAnICsgSlNPTi5zdHJpbmdpZnkoZS5kZXRhaWwpLnNsaWNlKDAsIDIyMCkpLmpvaW4oJ1xuJyk7CiAgICAgIHN0YXRlLm91dHB1dC52YWx1ZSA9IHRhaWw7CiAgICB9CiAgfQoKICBmdW5jdGlvbiBzZXRCdXR0b25Eb25lKGJ0biwgdGV4dCkgewogICAgY29uc3Qgb2xkID0gYnRuLnRleHRDb250ZW50OwogICAgYnRuLnRleHRDb250ZW50ID0gdGV4dDsKICAgIHNldFRpbWVvdXQoKCkgPT4geyBidG4udGV4dENvbnRlbnQgPSBvbGQ7IH0sIDE0MDApOwogIH0KCiAgZnVuY3Rpb24gaW5qZWN0U3R5bGVzKCkgewogICAgaWYgKGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKE5TICsgJy1zdHlsZScpKSByZXR1cm47CiAgICBjb25zdCBzdHlsZSA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3N0eWxlJyk7CiAgICBzdHlsZS5pZCA9IE5TICsgJy1zdHlsZSc7CiAgICBzdHlsZS50ZXh0Q29udGVudCA9CiAgICAgICcjYWR2LWRlYnVnLWxhdW5jaGVye3Bvc2l0aW9uOmZpeGVkO3JpZ2h0OjEyOHB4O2JvdHRvbToxNnB4O3otaW5kZXg6MjE0NzQ4MzY0NztiYWNrZ3JvdW5kOiMwZjc2NmU7Y29sb3I6I2ZmZjtib3JkZXI6bm9uZTtib3JkZXItcmFkaXVzOjk5OXB4O3BhZGRpbmc6MTBweCAxM3B4O2ZvbnQ6ODAwIDEycHgvMSBzeXN0ZW0tdWksU2Vnb2UgVUksQXJpYWw7Ym94LXNoYWRvdzowIDRweCAxNHB4IHJnYmEoMCwwLDAsLjM1KTtjdXJzb3I6cG9pbnRlcjt9JyArCiAgICAgICcjYWR2LWRlYnVnLXBhbmVse3Bvc2l0aW9uOmZpeGVkO3JpZ2h0OjE2cHg7Ym90dG9tOjcwcHg7d2lkdGg6NDQwcHg7bWF4LXdpZHRoOmNhbGMoMTAwdncgLSAzMnB4KTtiYWNrZ3JvdW5kOiMxMDE1MWY7Y29sb3I6I2RiZTdmNDtib3JkZXI6MXB4IHNvbGlkICMyYjNhNGI7Ym9yZGVyLXJhZGl1czoxMHB4O2JveC1zaGFkb3c6MCAxNHB4IDM0cHggcmdiYSgwLDAsMCwuNDUpO2Rpc3BsYXk6bm9uZTt6LWluZGV4OjIxNDc0ODM2NDc7Zm9udDoxM3B4LzEuMzUgc3lzdGVtLXVpLFNlZ29lIFVJLEFyaWFsO30nICsKICAgICAgJyNhZHYtZGVidWctcGFuZWwuc2hvd3tkaXNwbGF5OmJsb2NrO30nICsKICAgICAgJyNhZHYtZGVidWctcGFuZWwgLmFkLWhlYWR7ZGlzcGxheTpmbGV4O2FsaWduLWl0ZW1zOmNlbnRlcjtnYXA6OHB4O3BhZGRpbmc6MTBweCAxMnB4O2JvcmRlci1ib3R0b206MXB4IHNvbGlkICMyYjNhNGI7fScgKwogICAgICAnI2Fkdi1kZWJ1Zy1wYW5lbCAuYWQtdGl0bGV7Zm9udC13ZWlnaHQ6ODAwO2ZsZXg6MTt9JyArCiAgICAgICcjYWR2LWRlYnVnLXBhbmVsIC5hZC1jbG9zZXtiYWNrZ3JvdW5kOnRyYW5zcGFyZW50O2JvcmRlcjpub25lO2NvbG9yOiM5ZmIwYzM7Zm9udC1zaXplOjIwcHg7Y3Vyc29yOnBvaW50ZXI7fScgKwogICAgICAnI2Fkdi1kZWJ1Zy1wYW5lbCAuYWQtYm9keXtwYWRkaW5nOjEwcHggMTJweDt9JyArCiAgICAgICcjYWR2LWRlYnVnLXBhbmVsIC5hZC1yb3d7ZGlzcGxheTpmbGV4O2ZsZXgtd3JhcDp3cmFwO2dhcDo2cHg7bWFyZ2luLWJvdHRvbTo4cHg7fScgKwogICAgICAnI2Fkdi1kZWJ1Zy1wYW5lbCAuYWQtYnRue2JhY2tncm91bmQ6IzI1NjNlYjtjb2xvcjojZmZmO2JvcmRlcjpub25lO2JvcmRlci1yYWRpdXM6NnB4O3BhZGRpbmc6NnB4IDlweDtmb250OjcwMCAxMnB4LzEgc3lzdGVtLXVpLFNlZ29lIFVJLEFyaWFsO2N1cnNvcjpwb2ludGVyO30nICsKICAgICAgJyNhZHYtZGVidWctcGFuZWwgLmFkLWJ0bi5zZWNvbmRhcnl7YmFja2dyb3VuZDojMzM0MTU1O2NvbG9yOiNlMmU4ZjA7fScgKwogICAgICAnI2Fkdi1kZWJ1Zy1wYW5lbCAuYWQtYnRuLmRhbmdlcntiYWNrZ3JvdW5kOiNiOTFjMWM7fScgKwogICAgICAnI2Fkdi1kZWJ1Zy1wYW5lbCAuYWQtc3RhdHVze2NvbG9yOiNiN2M4ZGE7Zm9udC1zaXplOjEycHg7fScgKwogICAgICAnI2Fkdi1kZWJ1Zy1wYW5lbCB0ZXh0YXJlYXt3aWR0aDoxMDAlO21pbi1oZWlnaHQ6MTUwcHg7YmFja2dyb3VuZDojMGIxMTFhO2NvbG9yOiNkYmU3ZjQ7Ym9yZGVyOjFweCBzb2xpZCAjMjYzNDQ0O2JvcmRlci1yYWRpdXM6N3B4O3BhZGRpbmc6OHB4O2ZvbnQ6MTJweC8xLjM1IHVpLW1vbm9zcGFjZSxTRk1vbm8tUmVndWxhcixNZW5sbyxDb25zb2xhcyxtb25vc3BhY2U7cmVzaXplOnZlcnRpY2FsO30nICsKICAgICAgJyNhZHYtZGVidWctcGFuZWwgLmFkLW5vdGV7Zm9udC1zaXplOjExcHg7Y29sb3I6IzlmYjBjMzttYXJnaW4tdG9wOjZweDt9JzsKICAgIChkb2N1bWVudC5oZWFkIHx8IGRvY3VtZW50LmRvY3VtZW50RWxlbWVudCkuYXBwZW5kQ2hpbGQoc3R5bGUpOwogIH0KCiAgZnVuY3Rpb24gYnVpbGRVSSgpIHsKICAgIGlmICghZG9jdW1lbnQuYm9keSB8fCBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYWR2LWRlYnVnLWxhdW5jaGVyJykpIHJldHVybjsKICAgIGluamVjdFN0eWxlcygpOwogICAgY29uc3QgbGF1bmNoZXIgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdidXR0b24nKTsKICAgIGxhdW5jaGVyLmlkID0gJ2Fkdi1kZWJ1Zy1sYXVuY2hlcic7CiAgICBsYXVuY2hlci5jbGFzc05hbWUgPSBVSV9DTEFTUzsKICAgIGxhdW5jaGVyLnRleHRDb250ZW50ID0gJ0RCRyc7CiAgICBsYXVuY2hlci50aXRsZSA9ICdPcGVuIEFkdmFuY2VkIERlYnVnIFJlY29yZGVyIChDdHJsL0NtZCArIEFsdCArIEQpJzsKCiAgICBjb25zdCBwYW5lbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2RpdicpOwogICAgcGFuZWwuaWQgPSAnYWR2LWRlYnVnLXBhbmVsJzsKICAgIHBhbmVsLmNsYXNzTmFtZSA9IFVJX0NMQVNTOwogICAgcGFuZWwuaW5uZXJIVE1MID0KICAgICAgJzxkaXYgY2xhc3M9ImFkLWhlYWQiPicgKwogICAgICAnPGRpdiBjbGFzcz0iYWQtdGl0bGUiPkFkdmFuY2VkIERlYnVnIFJlY29yZGVyPC9kaXY+JyArCiAgICAgICc8ZGl2IGNsYXNzPSJhZC1zdGF0dXMiPjwvZGl2PicgKwogICAgICAnPGJ1dHRvbiBjbGFzcz0iYWQtY2xvc2UiIGFyaWEtbGFiZWw9IkNsb3NlIj54PC9idXR0b24+JyArCiAgICAgICc8L2Rpdj4nICsKICAgICAgJzxkaXYgY2xhc3M9ImFkLWJvZHkiPicgKwogICAgICAnPGRpdiBjbGFzcz0iYWQtcm93Ij4nICsKICAgICAgJzxidXR0b24gY2xhc3M9ImFkLWJ0biIgZGF0YS1hY3Q9InRvZ2dsZSI+PC9idXR0b24+JyArCiAgICAgICc8YnV0dG9uIGNsYXNzPSJhZC1idG4gc2Vjb25kYXJ5IiBkYXRhLWFjdD0ic25hcHNob3QiPlNuYXBzaG90PC9idXR0b24+JyArCiAgICAgICc8YnV0dG9uIGNsYXNzPSJhZC1idG4gc2Vjb25kYXJ5IiBkYXRhLWFjdD0iY29weSI+Q29weSBBSSBDb250ZXh0PC9idXR0b24+JyArCiAgICAgICc8YnV0dG9uIGNsYXNzPSJhZC1idG4gc2Vjb25kYXJ5IiBkYXRhLWFjdD0iZG93bmxvYWQiPkRvd25sb2FkIEpTT048L2J1dHRvbj4nICsKICAgICAgJzxidXR0b24gY2xhc3M9ImFkLWJ0biBkYW5nZXIiIGRhdGEtYWN0PSJjbGVhciI+Q2xlYXI8L2J1dHRvbj4nICsKICAgICAgJzwvZGl2PicgKwogICAgICAnPHRleHRhcmVhIHJlYWRvbmx5IHNwZWxsY2hlY2s9ImZhbHNlIiBhcmlhLWxhYmVsPSJSZWNlbnQgYWR2YW5jZWQgZGVidWcgZXZlbnRzIj48L3RleHRhcmVhPicgKwogICAgICAnPGRpdiBjbGFzcz0iYWQtbm90ZSI+QmVzdCBlZmZvcnQgY2FwdHVyZTogVUkgZXZlbnRzLCBjb25zb2xlL2Vycm9ycywgZmV0Y2gvWEhSLCBoaXN0b3J5L3N0b3JhZ2UsIERPTSBtdXRhdGlvbnMsIHN0YXRlIHNuYXBzaG90cywgZXZlbnQgbGlzdGVuZXIgY2FsbGJhY2tzLCB0aW1lcnMsIGFuZCBtYW51YWxseSB3cmFwcGVkIGZ1bmN0aW9ucy48L2Rpdj4nICsKICAgICAgJzwvZGl2Pic7CgogICAgZG9jdW1lbnQuYm9keS5hcHBlbmRDaGlsZChsYXVuY2hlcik7CiAgICBkb2N1bWVudC5ib2R5LmFwcGVuZENoaWxkKHBhbmVsKTsKICAgIHN0YXRlLnBhbmVsID0gcGFuZWw7CiAgICBzdGF0ZS5zdGF0dXMgPSBwYW5lbC5xdWVyeVNlbGVjdG9yKCcuYWQtc3RhdHVzJyk7CiAgICBzdGF0ZS5vdXRwdXQgPSBwYW5lbC5xdWVyeVNlbGVjdG9yKCd0ZXh0YXJlYScpOwoKICAgIGZ1bmN0aW9uIHJlZnJlc2hUb2dnbGUoKSB7CiAgICAgIGNvbnN0IGJ0biA9IHBhbmVsLnF1ZXJ5U2VsZWN0b3IoJ1tkYXRhLWFjdD0idG9nZ2xlIl0nKTsKICAgICAgYnRuLnRleHRDb250ZW50ID0gc3RhdGUucmVjb3JkaW5nID8gJ1BhdXNlJyA6ICdSZXN1bWUnOwogICAgfQoKICAgIGxhdW5jaGVyLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4gewogICAgICBwYW5lbC5jbGFzc0xpc3QudG9nZ2xlKCdzaG93Jyk7CiAgICAgIHVwZGF0ZVN0YXR1cygpOwogICAgICByZWZyZXNoVG9nZ2xlKCk7CiAgICB9KTsKICAgIHBhbmVsLnF1ZXJ5U2VsZWN0b3IoJy5hZC1jbG9zZScpLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKCkgPT4gcGFuZWwuY2xhc3NMaXN0LnJlbW92ZSgnc2hvdycpKTsKICAgIHBhbmVsLnF1ZXJ5U2VsZWN0b3IoJ1tkYXRhLWFjdD0idG9nZ2xlIl0nKS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsICgpID0+IHsKICAgICAgc3RhdGUucmVjb3JkaW5nID0gIXN0YXRlLnJlY29yZGluZzsKICAgICAgcmVjb3JkKHN0YXRlLnJlY29yZGluZyA/ICdyZWNvcmRlci5yZXN1bWUnIDogJ3JlY29yZGVyLnBhdXNlJywge30sIHsgZm9yY2U6IHRydWUgfSk7CiAgICAgIHJlZnJlc2hUb2dnbGUoKTsKICAgICAgdXBkYXRlU3RhdHVzKCk7CiAgICB9KTsKICAgIHBhbmVsLnF1ZXJ5U2VsZWN0b3IoJ1tkYXRhLWFjdD0ic25hcHNob3QiXScpLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKGUpID0+IHsKICAgICAgY2FwdHVyZVNuYXBzaG90KCdtYW51YWwnKTsKICAgICAgc2V0QnV0dG9uRG9uZShlLmN1cnJlbnRUYXJnZXQsICdDYXB0dXJlZCcpOwogICAgICB1cGRhdGVTdGF0dXMoKTsKICAgIH0pOwogICAgcGFuZWwucXVlcnlTZWxlY3RvcignW2RhdGEtYWN0PSJjb3B5Il0nKS5hZGRFdmVudExpc3RlbmVyKCdjbGljaycsIGFzeW5jIChlKSA9PiB7CiAgICAgIGNvbnN0IG9rID0gYXdhaXQgY29weVRleHQoZXhwb3J0VGV4dCgpKTsKICAgICAgc2V0QnV0dG9uRG9uZShlLmN1cnJlbnRUYXJnZXQsIG9rID8gJ0NvcGllZCcgOiAnQ29weSBmYWlsZWQnKTsKICAgICAgdXBkYXRlU3RhdHVzKCk7CiAgICB9KTsKICAgIHBhbmVsLnF1ZXJ5U2VsZWN0b3IoJ1tkYXRhLWFjdD0iZG93bmxvYWQiXScpLmFkZEV2ZW50TGlzdGVuZXIoJ2NsaWNrJywgKGUpID0+IHsKICAgICAgZG93bmxvYWRUZXh0KGV4cG9ydFRleHQoKSk7CiAgICAgIHNldEJ1dHRvbkRvbmUoZS5jdXJyZW50VGFyZ2V0LCAnRG93bmxvYWRlZCcpOwogICAgICB1cGRhdGVTdGF0dXMoKTsKICAgIH0pOwogICAgcGFuZWwucXVlcnlTZWxlY3RvcignW2RhdGEtYWN0PSJjbGVhciJdJykuYWRkRXZlbnRMaXN0ZW5lcignY2xpY2snLCAoKSA9PiB7CiAgICAgIGlmICghY29uZmlybSgnQ2xlYXIgYWR2YW5jZWQgZGVidWcgc2Vzc2lvbiBldmVudHMgYW5kIHNuYXBzaG90cz8nKSkgcmV0dXJuOwogICAgICBzdGF0ZS5ldmVudHMgPSBbXTsKICAgICAgc3RhdGUuc25hcHNob3RzID0gW107CiAgICAgIHN0YXRlLmNvdW50ZXJzID0ge307CiAgICAgIHJlY29yZCgncmVjb3JkZXIuY2xlYXInLCB7fSwgeyBmb3JjZTogdHJ1ZSB9KTsKICAgICAgdXBkYXRlU3RhdHVzKCk7CiAgICB9KTsKICAgIHJlZnJlc2hUb2dnbGUoKTsKICAgIHVwZGF0ZVN0YXR1cygpOwogIH0KCiAgZnVuY3Rpb24gd2hlbkJvZHlSZWFkeShjYikgewogICAgaWYgKGRvY3VtZW50LmJvZHkpIHJldHVybiBjYigpOwogICAgZG9jdW1lbnQuYWRkRXZlbnRMaXN0ZW5lcignRE9NQ29udGVudExvYWRlZCcsIGNiLCB7IG9uY2U6IHRydWUgfSk7CiAgfQoKICBmdW5jdGlvbiBiaW5kVWlFdmVudHMoKSB7CiAgICBjb25zdCBldmVudFR5cGVzID0gWydjbGljaycsICdkYmxjbGljaycsICdjb250ZXh0bWVudScsICdwb2ludGVyZG93bicsICdwb2ludGVydXAnLCAnaW5wdXQnLCAnY2hhbmdlJywgJ3N1Ym1pdCcsICdrZXlkb3duJywgJ2tleXVwJywgJ2ZvY3VzaW4nLCAnZm9jdXNvdXQnXTsKICAgIGV2ZW50VHlwZXMuZm9yRWFjaCgodHlwZSkgPT4gewogICAgICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKHR5cGUsIChlKSA9PiB7CiAgICAgICAgaWYgKGlzVWkoZS50YXJnZXQpKSByZXR1cm47CiAgICAgICAgaWYgKHR5cGUgPT09ICdwb2ludGVyZG93bicgfHwgdHlwZSA9PT0gJ3BvaW50ZXJ1cCcpIHsKICAgICAgICAgIGNvbnN0IHQgPSBwZXJmb3JtYW5jZS5ub3coKTsKICAgICAgICAgIGlmICh0IC0gc3RhdGUubGFzdFBvaW50ZXJBdCA8IDgwKSByZXR1cm47CiAgICAgICAgICBzdGF0ZS5sYXN0UG9pbnRlckF0ID0gdDsKICAgICAgICB9CiAgICAgICAgaWYgKHR5cGUgPT09ICdpbnB1dCcpIHsKICAgICAgICAgIGNvbnN0IHNlbCA9IGdldFNlbGVjdG9yKGUudGFyZ2V0KSB8fCAnJzsKICAgICAgICAgIGNvbnN0IHByZXYgPSBzdGF0ZS5sYXN0SW5wdXRCeVNlbGVjdG9yLmdldChzZWwpIHx8IDA7CiAgICAgICAgICBjb25zdCB0ID0gcGVyZm9ybWFuY2Uubm93KCk7CiAgICAgICAgICBpZiAodCAtIHByZXYgPCAyNTApIHJldHVybjsKICAgICAgICAgIHN0YXRlLmxhc3RJbnB1dEJ5U2VsZWN0b3Iuc2V0KHNlbCwgdCk7CiAgICAgICAgfQogICAgICAgIHJlY29yZCgndWkuJyArIHR5cGUsIHN1bW1hcml6ZUV2ZW50KGUpKTsKICAgICAgfSwgdHJ1ZSk7CiAgICB9KTsKICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdzY3JvbGwnLCAoKSA9PiB7CiAgICAgIGNvbnN0IHQgPSBwZXJmb3JtYW5jZS5ub3coKTsKICAgICAgaWYgKHQgLSBzdGF0ZS5sYXN0U2Nyb2xsQXQgPCA1MDApIHJldHVybjsKICAgICAgc3RhdGUubGFzdFNjcm9sbEF0ID0gdDsKICAgICAgcmVjb3JkKCd1aS5zY3JvbGwnLCB7IHg6IE1hdGgucm91bmQod2luZG93LnNjcm9sbFggfHwgMCksIHk6IE1hdGgucm91bmQod2luZG93LnNjcm9sbFkgfHwgMCksIHRhcmdldDogJ3dpbmRvdycgfSk7CiAgICB9LCB0cnVlKTsKICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdyZXNpemUnLCAoKSA9PiByZWNvcmQoJ3VpLnJlc2l6ZScsIHsgd2lkdGg6IHdpbmRvdy5pbm5lcldpZHRoLCBoZWlnaHQ6IHdpbmRvdy5pbm5lckhlaWdodCwgZGV2aWNlUGl4ZWxSYXRpbzogd2luZG93LmRldmljZVBpeGVsUmF0aW8gfHwgMSB9KSk7CiAgICBkb2N1bWVudC5hZGRFdmVudExpc3RlbmVyKCd2aXNpYmlsaXR5Y2hhbmdlJywgKCkgPT4gcmVjb3JkKCdwYWdlLnZpc2liaWxpdHknLCB7IHZpc2liaWxpdHlTdGF0ZTogZG9jdW1lbnQudmlzaWJpbGl0eVN0YXRlIH0pKTsKICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdvbmxpbmUnLCAoKSA9PiByZWNvcmQoJ25ldHdvcmsub25saW5lJywgeyBvbmxpbmU6IHRydWUgfSkpOwogICAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ29mZmxpbmUnLCAoKSA9PiByZWNvcmQoJ25ldHdvcmsub2ZmbGluZScsIHsgb25saW5lOiBmYWxzZSB9KSk7CiAgfQoKICBmdW5jdGlvbiBwYXRjaENvbnNvbGUoKSB7CiAgICBbJ2xvZycsICdpbmZvJywgJ3dhcm4nLCAnZXJyb3InLCAnZGVidWcnXS5mb3JFYWNoKChsZXZlbCkgPT4gewogICAgICBvcmlnaW5hbFsnY29uc29sZS4nICsgbGV2ZWxdID0gY29uc29sZVtsZXZlbF0gPyBjb25zb2xlW2xldmVsXS5iaW5kKGNvbnNvbGUpIDogY29uc29sZS5sb2cuYmluZChjb25zb2xlKTsKICAgICAgY29uc29sZVtsZXZlbF0gPSBmdW5jdGlvbiBhZHZhbmNlZERlYnVnQ29uc29sZVdyYXBwZXIoKSB7CiAgICAgICAgcmVjb3JkKCdjb25zb2xlLicgKyBsZXZlbCwgeyBhcmdzOiBBcnJheS5mcm9tKGFyZ3VtZW50cykgfSwgeyBtYXhTdHJpbmc6IDgwMDAgfSk7CiAgICAgICAgcmV0dXJuIG9yaWdpbmFsWydjb25zb2xlLicgKyBsZXZlbF0uYXBwbHkoY29uc29sZSwgYXJndW1lbnRzKTsKICAgICAgfTsKICAgIH0pOwogIH0KCiAgZnVuY3Rpb24gcGF0Y2hFcnJvcnMoKSB7CiAgICBjb25zdCBwcmV2T25FcnJvciA9IHdpbmRvdy5vbmVycm9yOwogICAgd2luZG93Lm9uZXJyb3IgPSBmdW5jdGlvbiAobWVzc2FnZSwgc291cmNlLCBsaW5lbm8sIGNvbG5vLCBlcnJvcikgewogICAgICByZWNvcmRFcnJvcignZXJyb3Iud2luZG93JywgZXJyb3IgfHwgbWVzc2FnZSwgeyBzb3VyY2UsIGxpbmVubywgY29sbm8sIG1lc3NhZ2U6IFN0cmluZyhtZXNzYWdlIHx8ICcnKSB9KTsKICAgICAgaWYgKHR5cGVvZiBwcmV2T25FcnJvciA9PT0gJ2Z1bmN0aW9uJykgcmV0dXJuIHByZXZPbkVycm9yLmFwcGx5KHRoaXMsIGFyZ3VtZW50cyk7CiAgICAgIHJldHVybiBmYWxzZTsKICAgIH07CiAgICB3aW5kb3cuYWRkRXZlbnRMaXN0ZW5lcignZXJyb3InLCAoZSkgPT4gewogICAgICBpZiAoZSAmJiBlLnRhcmdldCAmJiBlLnRhcmdldCAhPT0gd2luZG93ICYmIGUudGFyZ2V0LnRhZ05hbWUpIHsKICAgICAgICByZWNvcmQoJ2Vycm9yLnJlc291cmNlJywgeyB0YWc6IGUudGFyZ2V0LnRhZ05hbWUsIHNyYzogZS50YXJnZXQuc3JjIHx8IGUudGFyZ2V0LmhyZWYgfHwgJycsIHRhcmdldDogc3VtbWFyaXplRWxlbWVudChlLnRhcmdldCkgfSwgeyBmb3JjZTogdHJ1ZSB9KTsKICAgICAgICByZXR1cm47CiAgICAgIH0KICAgICAgcmVjb3JkRXJyb3IoJ2Vycm9yLmV2ZW50JywgZS5lcnJvciB8fCBlLm1lc3NhZ2UgfHwgJ0Vycm9yRXZlbnQnLCB7IGZpbGVuYW1lOiBlLmZpbGVuYW1lLCBsaW5lbm86IGUubGluZW5vLCBjb2xubzogZS5jb2xubyB9KTsKICAgIH0sIHRydWUpOwogICAgd2luZG93LmFkZEV2ZW50TGlzdGVuZXIoJ3VuaGFuZGxlZHJlamVjdGlvbicsIChlKSA9PiB7CiAgICAgIHJlY29yZEVycm9yKCdlcnJvci51bmhhbmRsZWRyZWplY3Rpb24nLCBlLnJlYXNvbiB8fCAnVW5oYW5kbGVkIHJlamVjdGlvbicpOwogICAgfSk7CiAgfQoKICBmdW5jdGlvbiBwYXRjaE5ldHdvcmsoKSB7CiAgICBpZiAod2luZG93LmZldGNoICYmICF3aW5kb3cuX19hZHZhbmNlZERlYnVnRmV0Y2hQYXRjaGVkKSB7CiAgICAgIG9yaWdpbmFsLmZldGNoID0gd2luZG93LmZldGNoLmJpbmQod2luZG93KTsKICAgICAgd2luZG93LmZldGNoID0gYXN5bmMgZnVuY3Rpb24gYWR2YW5jZWREZWJ1Z0ZldGNoV3JhcHBlcihpbnB1dCwgaW5pdCkgewogICAgICAgIGNvbnN0IG1ldGhvZCA9IChpbml0ICYmIGluaXQubWV0aG9kKSB8fCAoaW5wdXQgJiYgaW5wdXQubWV0aG9kKSB8fCAnR0VUJzsKICAgICAgICBjb25zdCB1cmwgPSB0eXBlb2YgaW5wdXQgPT09ICdzdHJpbmcnID8gaW5wdXQgOiAoaW5wdXQgJiYgaW5wdXQudXJsKSB8fCBTdHJpbmcoaW5wdXQpOwogICAgICAgIGNvbnN0IHN0YXJ0ZWQgPSBwZXJmb3JtYW5jZS5ub3coKTsKICAgICAgICByZWNvcmQoJ25ldHdvcmsuZmV0Y2guc3RhcnQnLCB7IG1ldGhvZCwgdXJsLCBpbml0OiBzYWZlU2VyaWFsaXplKGluaXQsIHsgZGVwdGg6IDMsIG1heFN0cmluZzogMjAwMCB9KSB9KTsKICAgICAgICB0cnkgewogICAgICAgICAgY29uc3QgcmVzcG9uc2UgPSBhd2FpdCBvcmlnaW5hbC5mZXRjaC5hcHBseSh0aGlzLCBhcmd1bWVudHMpOwogICAgICAgICAgcmVjb3JkKCduZXR3b3JrLmZldGNoLmVuZCcsIHsgbWV0aG9kLCB1cmwsIGR1cmF0aW9uTXM6IE1hdGgucm91bmQocGVyZm9ybWFuY2Uubm93KCkgLSBzdGFydGVkKSwgcmVzcG9uc2UgfSk7CiAgICAgICAgICByZXR1cm4gcmVzcG9uc2U7CiAgICAgICAgfSBjYXRjaCAoZXJyKSB7CiAgICAgICAgICByZWNvcmRFcnJvcignbmV0d29yay5mZXRjaC5lcnJvcicsIGVyciwgeyBtZXRob2QsIHVybCwgZHVyYXRpb25NczogTWF0aC5yb3VuZChwZXJmb3JtYW5jZS5ub3coKSAtIHN0YXJ0ZWQpIH0pOwogICAgICAgICAgdGhyb3cgZXJyOwogICAgICAgIH0KICAgICAgfTsKICAgICAgd2luZG93Ll9fYWR2YW5jZWREZWJ1Z0ZldGNoUGF0Y2hlZCA9IHRydWU7CiAgICB9CiAgICBpZiAod2luZG93LlhNTEh0dHBSZXF1ZXN0ICYmICF3aW5kb3cuX19hZHZhbmNlZERlYnVnWGhyUGF0Y2hlZCkgewogICAgICBvcmlnaW5hbC54aHJPcGVuID0gWE1MSHR0cFJlcXVlc3QucHJvdG90eXBlLm9wZW47CiAgICAgIG9yaWdpbmFsLnhoclNlbmQgPSBYTUxIdHRwUmVxdWVzdC5wcm90b3R5cGUuc2VuZDsKICAgICAgWE1MSHR0cFJlcXVlc3QucHJvdG90eXBlLm9wZW4gPSBmdW5jdGlvbiBhZHZhbmNlZERlYnVnWGhyT3BlbihtZXRob2QsIHVybCkgewogICAgICAgIHRoaXMuX19hZHZhbmNlZERlYnVnUmVxdWVzdCA9IHsgbWV0aG9kLCB1cmwsIHN0YXJ0ZWQ6IDAgfTsKICAgICAgICByZXR1cm4gb3JpZ2luYWwueGhyT3Blbi5hcHBseSh0aGlzLCBhcmd1bWVudHMpOwogICAgICB9OwogICAgICBYTUxIdHRwUmVxdWVzdC5wcm90b3R5cGUuc2VuZCA9IGZ1bmN0aW9uIGFkdmFuY2VkRGVidWdYaHJTZW5kKGJvZHkpIHsKICAgICAgICBjb25zdCBpbmZvID0gdGhpcy5fX2FkdmFuY2VkRGVidWdSZXF1ZXN0IHx8IHt9OwogICAgICAgIGluZm8uc3RhcnRlZCA9IHBlcmZvcm1hbmNlLm5vdygpOwogICAgICAgIHJlY29yZCgnbmV0d29yay54aHIuc3RhcnQnLCB7IG1ldGhvZDogaW5mby5tZXRob2QsIHVybDogaW5mby51cmwsIGJvZHk6IGJvZHkgPyBzYWZlU2VyaWFsaXplKGJvZHksIHsgZGVwdGg6IDIsIG1heFN0cmluZzogMTUwMCB9KSA6IHVuZGVmaW5lZCB9KTsKICAgICAgICB0aGlzLmFkZEV2ZW50TGlzdGVuZXIoJ2xvYWRlbmQnLCAoKSA9PiB7CiAgICAgICAgICByZWNvcmQoJ25ldHdvcmsueGhyLmVuZCcsIHsgbWV0aG9kOiBpbmZvLm1ldGhvZCwgdXJsOiBpbmZvLnVybCwgc3RhdHVzOiB0aGlzLnN0YXR1cywgc3RhdHVzVGV4dDogdGhpcy5zdGF0dXNUZXh0LCBkdXJhdGlvbk1zOiBNYXRoLnJvdW5kKHBlcmZvcm1hbmNlLm5vdygpIC0gaW5mby5zdGFydGVkKSB9KTsKICAgICAgICB9KTsKICAgICAgICByZXR1cm4gb3JpZ2luYWwueGhyU2VuZC5hcHBseSh0aGlzLCBhcmd1bWVudHMpOwogICAgICB9OwogICAgICB3aW5kb3cuX19hZHZhbmNlZERlYnVnWGhyUGF0Y2hlZCA9IHRydWU7CiAgICB9CiAgfQoKICBmdW5jdGlvbiBwYXRjaEhpc3RvcnlBbmRTdG9yYWdlKCkgewogICAgWydwdXNoU3RhdGUnLCAncmVwbGFjZVN0YXRlJ10uZm9yRWFjaCgobmFtZSkgPT4gewogICAgICBpZiAoIWhpc3RvcnlbbmFtZV0pIHJldHVybjsKICAgICAgb3JpZ2luYWxbJ2hpc3RvcnkuJyArIG5hbWVdID0gaGlzdG9yeVtuYW1lXS5iaW5kKGhpc3RvcnkpOwogICAgICBoaXN0b3J5W25hbWVdID0gZnVuY3Rpb24gYWR2YW5jZWREZWJ1Z0hpc3RvcnlXcmFwcGVyKGRhdGEsIHRpdGxlLCB1cmwpIHsKICAgICAgICByZWNvcmQoJ2hpc3RvcnkuJyArIG5hbWUsIHsgZGF0YSwgdGl0bGUsIHVybCB9KTsKICAgICAgICBjb25zdCByZXN1bHQgPSBvcmlnaW5hbFsnaGlzdG9yeS4nICsgbmFtZV0uYXBwbHkoaGlzdG9yeSwgYXJndW1lbnRzKTsKICAgICAgICBjYXB0dXJlU25hcHNob3QoJ2hpc3RvcnkuJyArIG5hbWUpOwogICAgICAgIHJldHVybiByZXN1bHQ7CiAgICAgIH07CiAgICB9KTsKICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdwb3BzdGF0ZScsIChlKSA9PiByZWNvcmQoJ2hpc3RvcnkucG9wc3RhdGUnLCB7IHN0YXRlOiBlLnN0YXRlIH0pKTsKICAgIHdpbmRvdy5hZGRFdmVudExpc3RlbmVyKCdoYXNoY2hhbmdlJywgKCkgPT4gcmVjb3JkKCdoaXN0b3J5Lmhhc2hjaGFuZ2UnLCB7IGhyZWY6IGxvY2F0aW9uLmhyZWYgfSkpOwogICAgdHJ5IHsKICAgICAgb3JpZ2luYWwubG9jYWxTdG9yYWdlU2V0ID0gU3RvcmFnZS5wcm90b3R5cGUuc2V0SXRlbTsKICAgICAgb3JpZ2luYWwubG9jYWxTdG9yYWdlUmVtb3ZlID0gU3RvcmFnZS5wcm90b3R5cGUucmVtb3ZlSXRlbTsKICAgICAgb3JpZ2luYWwubG9jYWxTdG9yYWdlQ2xlYXIgPSBTdG9yYWdlLnByb3RvdHlwZS5jbGVhcjsKICAgICAgU3RvcmFnZS5wcm90b3R5cGUuc2V0SXRlbSA9IGZ1bmN0aW9uIGFkdmFuY2VkRGVidWdTdG9yYWdlU2V0SXRlbShrZXksIHZhbHVlKSB7CiAgICAgICAgcmVjb3JkKCdzdG9yYWdlLnNldEl0ZW0nLCB7IHN0b3JhZ2U6IHRoaXMgPT09IGxvY2FsU3RvcmFnZSA/ICdsb2NhbFN0b3JhZ2UnIDogJ3Nlc3Npb25TdG9yYWdlJywga2V5LCB2YWx1ZTogcmVkYWN0VmFsdWUoa2V5LCB2YWx1ZSkgfSk7CiAgICAgICAgcmV0dXJuIG9yaWdpbmFsLmxvY2FsU3RvcmFnZVNldC5hcHBseSh0aGlzLCBhcmd1bWVudHMpOwogICAgICB9OwogICAgICBTdG9yYWdlLnByb3RvdHlwZS5yZW1vdmVJdGVtID0gZnVuY3Rpb24gYWR2YW5jZWREZWJ1Z1N0b3JhZ2VSZW1vdmVJdGVtKGtleSkgewogICAgICAgIHJlY29yZCgnc3RvcmFnZS5yZW1vdmVJdGVtJywgeyBzdG9yYWdlOiB0aGlzID09PSBsb2NhbFN0b3JhZ2UgPyAnbG9jYWxTdG9yYWdlJyA6ICdzZXNzaW9uU3RvcmFnZScsIGtleSB9KTsKICAgICAgICByZXR1cm4gb3JpZ2luYWwubG9jYWxTdG9yYWdlUmVtb3ZlLmFwcGx5KHRoaXMsIGFyZ3VtZW50cyk7CiAgICAgIH07CiAgICAgIFN0b3JhZ2UucHJvdG90eXBlLmNsZWFyID0gZnVuY3Rpb24gYWR2YW5jZWREZWJ1Z1N0b3JhZ2VDbGVhcigpIHsKICAgICAgICByZWNvcmQoJ3N0b3JhZ2UuY2xlYXInLCB7IHN0b3JhZ2U6IHRoaXMgPT09IGxvY2FsU3RvcmFnZSA/ICdsb2NhbFN0b3JhZ2UnIDogJ3Nlc3Npb25TdG9yYWdlJyB9KTsKICAgICAgICByZXR1cm4gb3JpZ2luYWwubG9jYWxTdG9yYWdlQ2xlYXIuYXBwbHkodGhpcywgYXJndW1lbnRzKTsKICAgICAgfTsKICAgIH0gY2F0Y2gge30KICB9CgogIGZ1bmN0aW9uIHdyYXBDYWxsYmFjayhsYWJlbCwgZm4pIHsKICAgIGlmICh0eXBlb2YgZm4gIT09ICdmdW5jdGlvbicpIHJldHVybiBmbjsKICAgIGlmIChmbi5fX2FkdmFuY2VkRGVidWdXcmFwcGVkKSByZXR1cm4gZm47CiAgICBjb25zdCB3cmFwcGVkID0gZnVuY3Rpb24gYWR2YW5jZWREZWJ1Z0luc3RydW1lbnRlZENhbGxiYWNrKCkgewogICAgICBjb25zdCBzdGFydGVkID0gcGVyZm9ybWFuY2Uubm93KCk7CiAgICAgIHJlY29yZCgnZnVuY3Rpb24uY2FsbCcsIHsgbGFiZWwsIG5hbWU6IGZuLm5hbWUgfHwgJ2Fub255bW91cycsIGFyZ3M6IEFycmF5LmZyb20oYXJndW1lbnRzKSB9LCB7IGRlcHRoOiA0LCBtYXhTdHJpbmc6IDMwMDAgfSk7CiAgICAgIHRyeSB7CiAgICAgICAgY29uc3QgcmVzdWx0ID0gZm4uYXBwbHkodGhpcywgYXJndW1lbnRzKTsKICAgICAgICBpZiAocmVzdWx0ICYmIHR5cGVvZiByZXN1bHQudGhlbiA9PT0gJ2Z1bmN0aW9uJykgewogICAgICAgICAgcmV0dXJuIHJlc3VsdC50aGVuKCh2YWx1ZSkgPT4gewogICAgICAgICAgICByZWNvcmQoJ2Z1bmN0aW9uLnJlc29sdmUnLCB7IGxhYmVsLCBuYW1lOiBmbi5uYW1lIHx8ICdhbm9ueW1vdXMnLCBkdXJhdGlvbk1zOiBNYXRoLnJvdW5kKHBlcmZvcm1hbmNlLm5vdygpIC0gc3RhcnRlZCksIHJlc3VsdDogdmFsdWUgfSwgeyBkZXB0aDogNCwgbWF4U3RyaW5nOiAzMDAwIH0pOwogICAgICAgICAgICByZXR1cm4gdmFsdWU7CiAgICAgICAgICB9LCAoZXJyKSA9PiB7CiAgICAgICAgICAgIHJlY29yZEVycm9yKCdmdW5jdGlvbi5yZWplY3QnLCBlcnIsIHsgbGFiZWwsIG5hbWU6IGZuLm5hbWUgfHwgJ2Fub255bW91cycsIGR1cmF0aW9uTXM6IE1hdGgucm91bmQocGVyZm9ybWFuY2Uubm93KCkgLSBzdGFydGVkKSB9KTsKICAgICAgICAgICAgdGhyb3cgZXJyOwogICAgICAgICAgfSk7CiAgICAgICAgfQogICAgICAgIHJlY29yZCgnZnVuY3Rpb24ucmV0dXJuJywgeyBsYWJlbCwgbmFtZTogZm4ubmFtZSB8fCAnYW5vbnltb3VzJywgZHVyYXRpb25NczogTWF0aC5yb3VuZChwZXJmb3JtYW5jZS5ub3coKSAtIHN0YXJ0ZWQpLCByZXN1bHQgfSwgeyBkZXB0aDogNCwgbWF4U3RyaW5nOiAzMDAwIH0pOwogICAgICAgIHJldHVybiByZXN1bHQ7CiAgICAgIH0gY2F0Y2ggKGVycikgewogICAgICAgIHJlY29yZEVycm9yKCdmdW5jdGlvbi50aHJvdycsIGVyciwgeyBsYWJlbCwgbmFtZTogZm4ubmFtZSB8fCAnYW5vbnltb3VzJywgZHVyYXRpb25NczogTWF0aC5yb3VuZChwZXJmb3JtYW5jZS5ub3coKSAtIHN0YXJ0ZWQpIH0pOwogICAgICAgIHRocm93IGVycjsKICAgICAgfQogICAgfTsKICAgIHdyYXBwZWQuX19hZHZhbmNlZERlYnVnV3JhcHBlZCA9IHRydWU7CiAgICB3cmFwcGVkLl9fYWR2YW5jZWREZWJ1Z09yaWdpbmFsID0gZm47CiAgICByZXR1cm4gd3JhcHBlZDsKICB9CgogIGZ1bmN0aW9uIHBhdGNoQ2FsbGJhY2tzKCkgewogICAgaWYgKHR5cGVvZiBFdmVudFRhcmdldCAhPT0gJ3VuZGVmaW5lZCcgJiYgRXZlbnRUYXJnZXQucHJvdG90eXBlICYmICF3aW5kb3cuX19hZHZhbmNlZERlYnVnRXZlbnRUYXJnZXRQYXRjaGVkKSB7CiAgICAgIG9yaWdpbmFsLmFkZEV2ZW50TGlzdGVuZXIgPSBFdmVudFRhcmdldC5wcm90b3R5cGUuYWRkRXZlbnRMaXN0ZW5lcjsKICAgICAgb3JpZ2luYWwucmVtb3ZlRXZlbnRMaXN0ZW5lciA9IEV2ZW50VGFyZ2V0LnByb3RvdHlwZS5yZW1vdmVFdmVudExpc3RlbmVyOwogICAgICBFdmVudFRhcmdldC5wcm90b3R5cGUuYWRkRXZlbnRMaXN0ZW5lciA9IGZ1bmN0aW9uIGFkdmFuY2VkRGVidWdBZGRFdmVudExpc3RlbmVyKHR5cGUsIGxpc3RlbmVyLCBvcHRpb25zKSB7CiAgICAgICAgaWYgKHR5cGVvZiBsaXN0ZW5lciAhPT0gJ2Z1bmN0aW9uJyB8fCBpc1VpKHRoaXMpKSB7CiAgICAgICAgICByZXR1cm4gb3JpZ2luYWwuYWRkRXZlbnRMaXN0ZW5lci5jYWxsKHRoaXMsIHR5cGUsIGxpc3RlbmVyLCBvcHRpb25zKTsKICAgICAgICB9CiAgICAgICAgbGV0IHBlclRhcmdldCA9IGxpc3RlbmVyTWFwLmdldCh0aGlzKTsKICAgICAgICBpZiAoIXBlclRhcmdldCkgewogICAgICAgICAgcGVyVGFyZ2V0ID0gbmV3IE1hcCgpOwogICAgICAgICAgbGlzdGVuZXJNYXAuc2V0KHRoaXMsIHBlclRhcmdldCk7CiAgICAgICAgfQogICAgICAgIGxldCBieVR5cGUgPSBwZXJUYXJnZXQuZ2V0KFN0cmluZyh0eXBlKSk7CiAgICAgICAgaWYgKCFieVR5cGUpIHsKICAgICAgICAgIGJ5VHlwZSA9IG5ldyBXZWFrTWFwKCk7CiAgICAgICAgICBwZXJUYXJnZXQuc2V0KFN0cmluZyh0eXBlKSwgYnlUeXBlKTsKICAgICAgICB9CiAgICAgICAgbGV0IHdyYXBwZWQgPSBieVR5cGUuZ2V0KGxpc3RlbmVyKTsKICAgICAgICBpZiAoIXdyYXBwZWQpIHsKICAgICAgICAgIHdyYXBwZWQgPSB3cmFwQ2FsbGJhY2soJ2V2ZW50OicgKyB0eXBlLCBsaXN0ZW5lcik7CiAgICAgICAgICBieVR5cGUuc2V0KGxpc3RlbmVyLCB3cmFwcGVkKTsKICAgICAgICB9CiAgICAgICAgcmV0dXJuIG9yaWdpbmFsLmFkZEV2ZW50TGlzdGVuZXIuY2FsbCh0aGlzLCB0eXBlLCB3cmFwcGVkLCBvcHRpb25zKTsKICAgICAgfTsKICAgICAgRXZlbnRUYXJnZXQucHJvdG90eXBlLnJlbW92ZUV2ZW50TGlzdGVuZXIgPSBmdW5jdGlvbiBhZHZhbmNlZERlYnVnUmVtb3ZlRXZlbnRMaXN0ZW5lcih0eXBlLCBsaXN0ZW5lciwgb3B0aW9ucykgewogICAgICAgIGNvbnN0IHBlclRhcmdldCA9IGxpc3RlbmVyTWFwLmdldCh0aGlzKTsKICAgICAgICBjb25zdCBieVR5cGUgPSBwZXJUYXJnZXQgJiYgcGVyVGFyZ2V0LmdldChTdHJpbmcodHlwZSkpOwogICAgICAgIGNvbnN0IHdyYXBwZWQgPSBieVR5cGUgJiYgYnlUeXBlLmdldChsaXN0ZW5lcik7CiAgICAgICAgcmV0dXJuIG9yaWdpbmFsLnJlbW92ZUV2ZW50TGlzdGVuZXIuY2FsbCh0aGlzLCB0eXBlLCB3cmFwcGVkIHx8IGxpc3RlbmVyLCBvcHRpb25zKTsKICAgICAgfTsKICAgICAgd2luZG93Ll9fYWR2YW5jZWREZWJ1Z0V2ZW50VGFyZ2V0UGF0Y2hlZCA9IHRydWU7CiAgICB9CgogICAgb3JpZ2luYWwuc2V0VGltZW91dCA9IHdpbmRvdy5zZXRUaW1lb3V0LmJpbmQod2luZG93KTsKICAgIG9yaWdpbmFsLnNldEludGVydmFsID0gd2luZG93LnNldEludGVydmFsLmJpbmQod2luZG93KTsKICAgIG9yaWdpbmFsLnJlcXVlc3RBbmltYXRpb25GcmFtZSA9IHdpbmRvdy5yZXF1ZXN0QW5pbWF0aW9uRnJhbWUgPyB3aW5kb3cucmVxdWVzdEFuaW1hdGlvbkZyYW1lLmJpbmQod2luZG93KSA6IG51bGw7CiAgICB3aW5kb3cuc2V0VGltZW91dCA9IGZ1bmN0aW9uIGFkdmFuY2VkRGVidWdTZXRUaW1lb3V0KGZuLCBkZWxheSkgewogICAgICBpZiAodHlwZW9mIGZuID09PSAnZnVuY3Rpb24nKSBhcmd1bWVudHNbMF0gPSB3cmFwQ2FsbGJhY2soJ3NldFRpbWVvdXQ6JyArIGRlbGF5LCBmbik7CiAgICAgIHJldHVybiBvcmlnaW5hbC5zZXRUaW1lb3V0LmFwcGx5KHdpbmRvdywgYXJndW1lbnRzKTsKICAgIH07CiAgICB3aW5kb3cuc2V0SW50ZXJ2YWwgPSBmdW5jdGlvbiBhZHZhbmNlZERlYnVnU2V0SW50ZXJ2YWwoZm4sIGRlbGF5KSB7CiAgICAgIGlmICh0eXBlb2YgZm4gPT09ICdmdW5jdGlvbicpIGFyZ3VtZW50c1swXSA9IHdyYXBDYWxsYmFjaygnc2V0SW50ZXJ2YWw6JyArIGRlbGF5LCBmbik7CiAgICAgIHJldHVybiBvcmlnaW5hbC5zZXRJbnRlcnZhbC5hcHBseSh3aW5kb3csIGFyZ3VtZW50cyk7CiAgICB9OwogICAgaWYgKG9yaWdpbmFsLnJlcXVlc3RBbmltYXRpb25GcmFtZSkgewogICAgICB3aW5kb3cucmVxdWVzdEFuaW1hdGlvbkZyYW1lID0gZnVuY3Rpb24gYWR2YW5jZWREZWJ1Z1JlcXVlc3RBbmltYXRpb25GcmFtZShmbikgewogICAgICAgIHJldHVybiBvcmlnaW5hbC5yZXF1ZXN0QW5pbWF0aW9uRnJhbWUod3JhcENhbGxiYWNrKCdyZXF1ZXN0QW5pbWF0aW9uRnJhbWUnLCBmbikpOwogICAgICB9OwogICAgfQogIH0KCiAgZnVuY3Rpb24gb2JzZXJ2ZU11dGF0aW9ucygpIHsKICAgIGlmICghQ09ORklHLmNhcHR1cmVEb21NdXRhdGlvbnMgfHwgdHlwZW9mIE11dGF0aW9uT2JzZXJ2ZXIgIT09ICdmdW5jdGlvbicpIHJldHVybjsKICAgIGxldCBwZW5kaW5nID0gW107CiAgICBsZXQgdGltZXIgPSBudWxsOwogICAgc3RhdGUubXV0YXRpb25PYnNlcnZlciA9IG5ldyBNdXRhdGlvbk9ic2VydmVyKChtdXRhdGlvbnMpID0+IHsKICAgICAgbXV0YXRpb25zLmZvckVhY2goKG0pID0+IHsKICAgICAgICBpZiAoaXNVaShtLnRhcmdldCkpIHJldHVybjsKICAgICAgICBwZW5kaW5nLnB1c2goewogICAgICAgICAgdHlwZTogbS50eXBlLAogICAgICAgICAgdGFyZ2V0OiBzdW1tYXJpemVFbGVtZW50KG0udGFyZ2V0KSwKICAgICAgICAgIGF0dHJpYnV0ZU5hbWU6IG0uYXR0cmlidXRlTmFtZSB8fCAnJywKICAgICAgICAgIGFkZGVkOiBtLmFkZGVkTm9kZXMgPyBtLmFkZGVkTm9kZXMubGVuZ3RoIDogMCwKICAgICAgICAgIHJlbW92ZWQ6IG0ucmVtb3ZlZE5vZGVzID8gbS5yZW1vdmVkTm9kZXMubGVuZ3RoIDogMAogICAgICAgIH0pOwogICAgICB9KTsKICAgICAgaWYgKHRpbWVyKSByZXR1cm47CiAgICAgIHRpbWVyID0gc2V0VGltZW91dCgoKSA9PiB7CiAgICAgICAgY29uc3QgYmF0Y2ggPSBwZW5kaW5nLnNsaWNlKDAsIDUwKTsKICAgICAgICBjb25zdCBleHRyYSA9IHBlbmRpbmcubGVuZ3RoID4gNTAgPyBwZW5kaW5nLmxlbmd0aCAtIDUwIDogMDsKICAgICAgICBwZW5kaW5nID0gW107CiAgICAgICAgdGltZXIgPSBudWxsOwogICAgICAgIGlmIChiYXRjaC5sZW5ndGgpIHJlY29yZCgnZG9tLm11dGF0aW9uJywgeyBtdXRhdGlvbnM6IGJhdGNoLCB0cnVuY2F0ZWQ6IGV4dHJhIH0pOwogICAgICB9LCA1MDApOwogICAgfSk7CiAgICB3aGVuQm9keVJlYWR5KCgpID0+IHN0YXRlLm11dGF0aW9uT2JzZXJ2ZXIub2JzZXJ2ZShkb2N1bWVudC5ib2R5LCB7IGNoaWxkTGlzdDogdHJ1ZSwgc3VidHJlZTogdHJ1ZSwgYXR0cmlidXRlczogdHJ1ZSwgYXR0cmlidXRlRmlsdGVyOiBbJ2NsYXNzJywgJ3N0eWxlJywgJ2hpZGRlbicsICdkaXNhYmxlZCcsICdhcmlhLWV4cGFuZGVkJywgJ2FyaWEtaGlkZGVuJywgJ3ZhbHVlJ10gfSkpOwogIH0KCiAgZnVuY3Rpb24gYmluZFNob3J0Y3V0cygpIHsKICAgIGRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLCAoZSkgPT4gewogICAgICBjb25zdCBpc01hYyA9IG5hdmlnYXRvci5wbGF0Zm9ybS50b1VwcGVyQ2FzZSgpLmluY2x1ZGVzKCdNQUMnKTsKICAgICAgY29uc3QgbW9kID0gaXNNYWMgPyBlLm1ldGFLZXkgOiBlLmN0cmxLZXk7CiAgICAgIGlmIChtb2QgJiYgZS5hbHRLZXkgJiYgZS5rZXkudG9Mb3dlckNhc2UoKSA9PT0gJ2QnKSB7CiAgICAgICAgZS5wcmV2ZW50RGVmYXVsdCgpOwogICAgICAgIGlmIChzdGF0ZS5wYW5lbCkgc3RhdGUucGFuZWwuY2xhc3NMaXN0LnRvZ2dsZSgnc2hvdycpOwogICAgICAgIHVwZGF0ZVN0YXR1cygpOwogICAgICB9CiAgICB9LCB0cnVlKTsKICB9CgogIGZ1bmN0aW9uIGluc3RhbGxBcGkoKSB7CiAgICB3aW5kb3cuQWR2YW5jZWREZWJ1ZyA9IHsKICAgICAgc3RhdGUsCiAgICAgIHJlY29yZDogKHR5cGUsIGRldGFpbCkgPT4gcmVjb3JkKHR5cGUgfHwgJ2N1c3RvbScsIGRldGFpbCwgeyBmb3JjZTogdHJ1ZSB9KSwKICAgICAgc25hcHNob3Q6IChyZWFzb24pID0+IGNhcHR1cmVTbmFwc2hvdChyZWFzb24gfHwgJ2FwaScpLAogICAgICBleHBvcnQ6IGV4cG9ydFBheWxvYWQsCiAgICAgIGV4cG9ydFRleHQsCiAgICAgIGNvcHk6IGFzeW5jICgpID0+IGNvcHlUZXh0KGV4cG9ydFRleHQoKSksCiAgICAgIGRvd25sb2FkOiAoKSA9PiBkb3dubG9hZFRleHQoZXhwb3J0VGV4dCgpKSwKICAgICAgcGF1c2U6ICgpID0+IHsgc3RhdGUucmVjb3JkaW5nID0gZmFsc2U7IHJlY29yZCgncmVjb3JkZXIucGF1c2UnLCB7IHNvdXJjZTogJ2FwaScgfSwgeyBmb3JjZTogdHJ1ZSB9KTsgdXBkYXRlU3RhdHVzKCk7IH0sCiAgICAgIHJlc3VtZTogKCkgPT4geyBzdGF0ZS5yZWNvcmRpbmcgPSB0cnVlOyByZWNvcmQoJ3JlY29yZGVyLnJlc3VtZScsIHsgc291cmNlOiAnYXBpJyB9LCB7IGZvcmNlOiB0cnVlIH0pOyB1cGRhdGVTdGF0dXMoKTsgfSwKICAgICAgcmVnaXN0ZXJTdGF0ZVByb3ZpZGVyOiAobmFtZSwgZm4pID0+IHsKICAgICAgICBpZiAoIW5hbWUgfHwgdHlwZW9mIGZuICE9PSAnZnVuY3Rpb24nKSB0aHJvdyBuZXcgRXJyb3IoJ3JlZ2lzdGVyU3RhdGVQcm92aWRlcihuYW1lLCBmbikgcmVxdWlyZXMgYSBmdW5jdGlvbicpOwogICAgICAgIHN0YXRlUHJvdmlkZXJzLnNldChTdHJpbmcobmFtZSksIGZuKTsKICAgICAgfSwKICAgICAgdHJhY2tGdW5jdGlvbjogKG5hbWUsIGZuKSA9PiB3cmFwQ2FsbGJhY2sobmFtZSB8fCAoZm4gJiYgZm4ubmFtZSkgfHwgJ21hbnVhbCcsIGZuKSwKICAgICAgd3JhcE9iamVjdDogKG9iaiwgbGFiZWwpID0+IHsKICAgICAgICBpZiAoIW9iaiB8fCB0eXBlb2Ygb2JqICE9PSAnb2JqZWN0JykgcmV0dXJuIG9iajsKICAgICAgICBPYmplY3Qua2V5cyhvYmopLmZvckVhY2goKGtleSkgPT4gewogICAgICAgICAgaWYgKHR5cGVvZiBvYmpba2V5XSA9PT0gJ2Z1bmN0aW9uJyAmJiAhb2JqW2tleV0uX19hZHZhbmNlZERlYnVnV3JhcHBlZCkgewogICAgICAgICAgICBvYmpba2V5XSA9IHdyYXBDYWxsYmFjaygobGFiZWwgfHwgJ29iamVjdCcpICsgJy4nICsga2V5LCBvYmpba2V5XSk7CiAgICAgICAgICB9CiAgICAgICAgfSk7CiAgICAgICAgcmV0dXJuIG9iajsKICAgICAgfQogICAgfTsKICB9CgogIGluc3RhbGxBcGkoKTsKICBwYXRjaENhbGxiYWNrcygpOwogIHBhdGNoQ29uc29sZSgpOwogIHBhdGNoRXJyb3JzKCk7CiAgcGF0Y2hOZXR3b3JrKCk7CiAgcGF0Y2hIaXN0b3J5QW5kU3RvcmFnZSgpOwogIGJpbmRVaUV2ZW50cygpOwogIG9ic2VydmVNdXRhdGlvbnMoKTsKICBiaW5kU2hvcnRjdXRzKCk7CiAgd2hlbkJvZHlSZWFkeShidWlsZFVJKTsKICBjYXB0dXJlU25hcHNob3QoJ3N0YXJ0dXAnKTsKICBzdGF0ZS5zbmFwc2hvdFRpbWVyID0gc2V0SW50ZXJ2YWwoKCkgPT4gY2FwdHVyZVNuYXBzaG90KCdpbnRlcnZhbCcpLCBNYXRoLm1heCgxMDAwLCBOdW1iZXIoQ09ORklHLnNuYXBzaG90SW50ZXJ2YWxNcykgfHwgNTAwMCkpOwogIHJlY29yZCgncmVjb3JkZXIucmVhZHknLCB7IHNlc3Npb25JZDogc3RhdGUuc2Vzc2lvbklkLCBjb25maWc6IENPTkZJRyB9LCB7IGZvcmNlOiB0cnVlIH0pOwp9KSgpOwo=')));
    },


    async getAdvancedDebugCode() {
        try {
            const response = await fetch('advanceddebug.js', { cache: 'no-store' });
            if (!response.ok) throw new Error('HTTP ' + response.status);
            return await response.text();
        } catch (err) {
            console.warn('AdvancedDebug: failed to fetch local advanceddebug.js source; using embedded fallback copy.', err);
            return this.getEmbeddedAdvancedDebugCode();
        }
    },

    async copyAdvancedDebugCode() {
        try {
            const code = await this.getAdvancedDebugCode();
            await navigator.clipboard.writeText(code);
            const btn = $('#advanced-debug-copy-btn');
            const orig = btn.text();
            btn.text('Copied');
            setTimeout(() => btn.text(orig), 1500);
        } catch (err) {
            alert('Failed to copy advanceddebug.js: ' + err.message);
        }
    },

    async integrate(isUpdate) {
        if (!loadFolder || !loadFolder.fileHandle) {
            alert('Please load a directory first.');
            return;
        }
        if (isUpdate && !confirm('This will overwrite your existing advanceddebug.js file. Continue?')) {
            return;
        }

        const addBtn = $('#advanced-debug-add-btn');
        const updateBtn = $('#advanced-debug-update-btn');
        const progress = $('#advanced-debug-progress');
        const progressText = $('#advanced-debug-progress-text');
        const actionBtn = isUpdate ? updateBtn : addBtn;
        const otherBtn = isUpdate ? addBtn : updateBtn;
        const originalText = actionBtn.data('originalText') || actionBtn.text();
        actionBtn.data('originalText', originalText);

        actionBtn.prop('disabled', true).text('Working...');
        otherBtn.prop('disabled', true);
        progress.css('display', 'flex').removeClass('success error').addClass('loading');
        progressText.text(isUpdate ? 'Updating advanceddebug.js...' : 'Adding advanceddebug.js to your project...');

        try {
            const code = await this.getAdvancedDebugCode();
            await this._writeProjectFile('advanceddebug.js', code);
            const summary = await this._injectScriptTags();

            if (loadFolder.refreshFileTree && loadFolder.recursivelyReadDirectory) {
                loadFolder.fileStructure = await loadFolder.recursivelyReadDirectory([], loadFolder.fileHandle);
                loadFolder.refreshFileTree();
            }
            await this.checkStatus();

            progress.removeClass('loading error').addClass('success');
            progressText.text('advanceddebug.js integrated. Updated ' + summary.updated + ' HTML file(s).');
            setTimeout(() => {
                progress.css('display', 'none');
                progress.removeClass('success');
            }, 3500);

            actionBtn.prop('disabled', false).text('Done');
            setTimeout(() => actionBtn.prop('disabled', false).text(actionBtn.data('originalText') || originalText), 2200);
            otherBtn.prop('disabled', false);
        } catch (err) {
            console.error('AdvancedDebug integrate error:', err);
            progress.removeClass('loading success').addClass('error');
            progressText.text('Failed to integrate advanceddebug.js. See console.');
            setTimeout(() => {
                progress.css('display', 'none');
                progress.removeClass('error');
            }, 5000);
            actionBtn.prop('disabled', false).text(actionBtn.data('originalText') || originalText);
            otherBtn.prop('disabled', false);
            alert('Error: ' + err.message);
        } finally {
            progress.removeClass('loading');
        }
    },

    async _writeProjectFile(filename, content) {
        const fileHandle = await loadFolder.fileHandle.getFileHandle(filename, { create: true });
        const writable = await fileHandle.createWritable();
        try {
            await writable.write(content);
        } finally {
            await writable.close();
        }
    },

    async _injectScriptTags() {
        const result = { total: 0, updated: 0, alreadyPresent: 0, missingHead: 0, failures: [] };
        const files = Array.isArray(loadFolder.fileStructure) ? loadFolder.fileStructure : [];
        const htmlFiles = files.filter(f => f && f.kind === 'file' && /\.html?$/i.test(f.name || ''));
        result.total = htmlFiles.length;

        for (const file of htmlFiles) {
            try {
                const outcome = await this._injectScriptTag(file);
                if (outcome === 'updated') result.updated += 1;
                if (outcome === 'already-present') result.alreadyPresent += 1;
                if (outcome === 'missing-head') result.missingHead += 1;
            } catch (err) {
                result.failures.push({ path: file.relativePath || file.name, error: err.message });
                console.error('AdvancedDebug: failed to update HTML file:', file.relativePath || file.name, err);
            }
        }
        return result;
    },

    _findOpenEditorByRelativePath(relativePath) {
        if (typeof editor === 'undefined' || !editor || !editor._meta) return null;
        for (const [uuid, meta] of Object.entries(editor._meta)) {
            if (meta && meta.relativePath === relativePath) {
                return { uuid, meta, view: editor.instance ? editor.instance[uuid] : null };
            }
        }
        return null;
    },

    async _readFileContent(file) {
        const openInfo = this._findOpenEditorByRelativePath(file.relativePath);
        if (openInfo && openInfo.view) return openInfo.view.state.doc.toString();
        if (loadFolder.getFileContent) return await loadFolder.getFileContent(file);
        const blob = await file.entry.getFile();
        return await blob.text();
    },

    _computeRelativeScriptPath(relativePath) {
        const dir = relativePath && relativePath.includes('/') ? relativePath.substring(0, relativePath.lastIndexOf('/')) : '';
        if (!dir) return 'advanceddebug.js';
        const depth = dir.split('/').filter(Boolean).length;
        return '../'.repeat(depth) + 'advanceddebug.js';
    },

    async _writeHtmlFile(file, content) {
        let prepared = content;
        if (typeof editor !== 'undefined' && editor.ensureUnshippedBanner) {
            prepared = editor.ensureUnshippedBanner(prepared);
        }
        const writable = await file.entry.createWritable();
        try {
            await writable.write(prepared);
        } finally {
            await writable.close();
        }
        file.text = prepared;

        const openInfo = this._findOpenEditorByRelativePath(file.relativePath);
        if (openInfo && openInfo.view) {
            const current = openInfo.view.state.doc.toString();
            if (current !== prepared) {
                openInfo.view.dispatch({ changes: { from: 0, to: current.length, insert: prepared } });
            }
            if (openInfo.meta) openInfo.meta.text = prepared;
            if (editor.dirtyFiles) editor.dirtyFiles.delete(openInfo.uuid);
            if (typeof editor._setStatus === 'function') editor._setStatus(openInfo.uuid, 'Saved', 'saved');
        }
    },

    async _injectScriptTag(file) {
        const content = await this._readFileContent(file);
        if (/advanceddebug\.js/i.test(content)) return 'already-present';
        const headMatch = content.match(/(<head[^>]*>)/i);
        if (!headMatch) return 'missing-head';
        const scriptPath = this._computeRelativeScriptPath(file.relativePath || file.name);
        const tag = '\n    <\x73cript src="' + scriptPath + '"></script>';
        const next = content.replace(headMatch[0], headMatch[0] + tag);
        if (next === content) return 'already-present';
        await this._writeHtmlFile(file, next);
        return 'updated';
    }
};
